// =====================================================
// HealthyBlood — Heart-Healthy Recipe Library
// Organized by category. Every recipe is built around
// Mediterranean / heart-healthy principles:
//   - Whole grains, legumes, leafy greens, colorful produce
//   - Olive oil, nuts, seeds, omega-3 fish
//   - Minimal processed foods, added sugars, and sodium
// =====================================================
window.RECIPES = [

  // ================================================
  // BREAKFAST
  // ================================================
  {
    id: "oats",
    cat: "breakfast",
    emoji: "🥣",
    title: "Berry Almond Overnight Oats",
    time: "5 min prep",
    calories: "320 cal",
    summary: "A creamy, fiber-rich breakfast that helps escort cholesterol out of your body.",
    benefit: "Soluble fiber from oats binds to LDL cholesterol in your gut. Berries add antioxidants that protect your arteries.",
    ingredients: ["1/2 cup rolled oats", "1/2 cup unsweetened almond milk", "1 tbsp chia seeds", "1/4 cup mixed berries", "1 tbsp slivered almonds", "1 tsp honey or maple syrup", "Pinch of cinnamon"],
    instructions: ["Combine oats, almond milk, and chia seeds in a jar.", "Stir well, then top with berries, almonds, sweetener, and cinnamon.", "Cover and refrigerate overnight (or at least 4 hours).", "Enjoy cold in the morning. Add a splash more milk if too thick."],
  },
  {
    id: "avotoast",
    cat: "breakfast",
    emoji: "🥑",
    title: "Avocado Toast with Seeds",
    time: "5 min",
    calories: "290 cal",
    summary: "Creamy avocado on whole-grain toast — quick, satisfying, heart-friendly.",
    benefit: "Avocado's monounsaturated fats support healthy HDL levels. Whole grains add fiber and slow-release energy.",
    ingredients: ["1 slice whole-grain sourdough", "1/2 ripe avocado", "1 tsp pumpkin seeds", "1 tsp hemp hearts", "Squeeze of lemon", "Pinch of red pepper flakes", "Salt and pepper"],
    instructions: ["Toast the bread until golden.", "Mash avocado with lemon, salt, and pepper.", "Spread thickly on toast.", "Top with seeds and red pepper flakes. Eat right away."],
  },
  {
    id: "veggieomelet",
    cat: "breakfast",
    emoji: "🍳",
    title: "Veggie Omelet with Spinach",
    time: "10 min",
    calories: "260 cal",
    summary: "Protein-packed omelet loaded with spinach, tomatoes, and herbs.",
    benefit: "Eggs deliver high-quality protein while spinach adds folate and magnesium — both support healthy blood pressure.",
    ingredients: ["2 large eggs", "1 cup baby spinach", "1/4 cup cherry tomatoes, halved", "1 tsp olive oil", "1 tbsp fresh herbs (parsley, chives)", "Salt and pepper"],
    instructions: ["Whisk eggs with salt and pepper.", "Heat olive oil in a nonstick skillet over medium heat.", "Add spinach and tomatoes; cook 1 min until wilted.", "Pour in eggs. Tilt pan to spread evenly.", "Cook 2-3 min, fold in half, and slide onto a plate."],
  },
  {
    id: "steelcut",
    cat: "breakfast",
    emoji: "🌰",
    title: "Steel-Cut Oats with Walnuts & Banana",
    time: "25 min",
    calories: "340 cal",
    summary: "Hearty steel-cut oats topped with omega-3 rich walnuts and fresh banana.",
    benefit: "Steel-cut oats have a lower glycemic impact than rolled oats. Walnuts are one of the best plant sources of omega-3 ALA.",
    ingredients: ["1/4 cup steel-cut oats", "1 cup water", "1/2 banana, sliced", "2 tbsp chopped walnuts", "1 tsp maple syrup", "1/2 tsp cinnamon"],
    instructions: ["Bring water to a boil in a small pot.", "Stir in oats, reduce heat, and simmer 20 min stirring occasionally.", "Spoon into a bowl; top with banana, walnuts, maple syrup, and cinnamon."],
  },
  {
    id: "yogurtparfait",
    cat: "breakfast",
    emoji: "🍓",
    title: "Greek Yogurt Berry Parfait",
    time: "5 min",
    calories: "280 cal",
    summary: "Layered parfait with plain Greek yogurt, berries, and homemade granola.",
    benefit: "Greek yogurt delivers probiotics and protein. Berries bring heart-protective anthocyanins.",
    ingredients: ["3/4 cup plain 2% Greek yogurt", "1/2 cup mixed berries", "2 tbsp low-sugar granola", "1 tsp ground flaxseed", "1 tsp honey"],
    instructions: ["Spoon half the yogurt into a glass.", "Layer half the berries and granola.", "Repeat with remaining yogurt, berries, and granola.", "Sprinkle flaxseed and drizzle honey on top."],
  },
  {
    id: "wgpancakes",
    cat: "breakfast",
    emoji: "🥞",
    title: "Whole-Grain Pancakes with Blueberries",
    time: "15 min",
    calories: "310 cal",
    summary: "Fluffy whole-grain pancakes studded with fresh blueberries.",
    benefit: "Whole-grain flour keeps fiber and B-vitamins intact. Blueberries deliver heart-friendly polyphenols.",
    ingredients: ["1/2 cup whole-wheat flour", "1/2 tsp baking powder", "1/2 cup low-fat milk", "1 egg", "1 tbsp olive oil", "1/3 cup blueberries", "1 tsp maple syrup"],
    instructions: ["Whisk flour and baking powder in a bowl.", "In another bowl, beat milk, egg, and oil.", "Combine wet into dry. Fold in blueberries.", "Cook 1/4 cup portions on a nonstick pan 2 min per side.", "Top with a drizzle of maple syrup."],
  },
  {
    id: "chiapudding",
    cat: "breakfast",
    emoji: "🥥",
    title: "Coconut Chia Seed Pudding",
    time: "5 min prep",
    calories: "300 cal",
    summary: "A spoonable pudding packed with omega-3s and plant fiber.",
    benefit: "Chia seeds are loaded with ALA omega-3s and soluble fiber — a one-two punch for heart health.",
    ingredients: ["3 tbsp chia seeds", "1 cup unsweetened coconut milk", "1 tsp maple syrup", "1/2 tsp vanilla extract", "1/4 cup raspberries", "1 tbsp unsweetened coconut flakes"],
    instructions: ["Whisk chia, coconut milk, syrup, and vanilla in a jar.", "Stir again after 5 min to prevent clumping.", "Refrigerate at least 4 hours or overnight.", "Top with raspberries and coconut flakes before eating."],
  },
  {
    id: "sweetpotatohash",
    cat: "breakfast",
    emoji: "🍠",
    title: "Sweet Potato Hash with Eggs",
    time: "20 min",
    calories: "360 cal",
    summary: "Savory hash of sweet potato, peppers, and eggs — weekend breakfast energy.",
    benefit: "Sweet potatoes are rich in potassium and beta-carotene, both of which support healthy blood vessels.",
    ingredients: ["1 small sweet potato, diced", "1/2 bell pepper, diced", "1/4 onion, diced", "1 tbsp olive oil", "2 eggs", "1/2 tsp paprika", "Salt and pepper"],
    instructions: ["Heat olive oil in a skillet over medium heat.", "Add sweet potato; cook 8 min until tender.", "Add pepper, onion, paprika. Cook 4 more min.", "Make two wells, crack eggs into them.", "Cover, cook 3 min until whites set. Season and serve."],
  },
  {
    id: "quinoabowl",
    cat: "breakfast",
    emoji: "🍯",
    title: "Quinoa Breakfast Bowl",
    time: "10 min (cooked quinoa)",
    calories: "330 cal",
    summary: "A warm, protein-packed breakfast alternative to oatmeal.",
    benefit: "Quinoa is a complete plant protein and delivers fiber, iron, and magnesium.",
    ingredients: ["1/2 cup cooked quinoa", "1/2 cup unsweetened almond milk", "1/2 apple, diced", "1 tbsp walnuts", "1/2 tsp cinnamon", "1 tsp honey"],
    instructions: ["Warm quinoa with almond milk in a small pot.", "Stir in cinnamon.", "Spoon into a bowl; top with apple, walnuts, and honey."],
  },
  {
    id: "medeggcups",
    cat: "breakfast",
    emoji: "🧁",
    title: "Mediterranean Egg Cups",
    time: "25 min",
    calories: "180 cal (2 cups)",
    summary: "Portable baked egg cups with spinach, feta, and tomato.",
    benefit: "Grab-and-go protein with veggies and the healthy fats of feta in moderation.",
    ingredients: ["6 large eggs", "1 cup baby spinach, chopped", "1/4 cup crumbled feta", "1/4 cup diced tomato", "1 tbsp olive oil", "Salt and pepper"],
    instructions: ["Preheat oven to 375°F (190°C).", "Grease a 6-cup muffin tin with olive oil.", "Whisk eggs, salt, and pepper.", "Divide spinach, feta, and tomato into cups.", "Pour egg over each; bake 18-20 min until set."],
  },
  {
    id: "applecinn",
    cat: "breakfast",
    emoji: "🍎",
    title: "Apple Cinnamon Oatmeal",
    time: "10 min",
    calories: "290 cal",
    summary: "Warm oatmeal with sautéed apples and cinnamon — like dessert for breakfast.",
    benefit: "Apples and oats both contain pectin, a soluble fiber that supports healthy cholesterol.",
    ingredients: ["1/2 cup rolled oats", "1 cup water or almond milk", "1 apple, diced", "1 tsp cinnamon", "1 tbsp walnuts", "1 tsp maple syrup"],
    instructions: ["Cook oats in water per package directions.", "Meanwhile, sauté apple with cinnamon in a dry pan 4 min.", "Top cooked oats with apples, walnuts, and maple syrup."],
  },
  {
    id: "salmonbagel",
    cat: "breakfast",
    emoji: "🥯",
    title: "Smoked Salmon Whole-Grain Bagel",
    time: "5 min",
    calories: "380 cal",
    summary: "A classic open-faced breakfast with omega-3 rich salmon.",
    benefit: "Smoked salmon is one of the best sources of heart-supportive omega-3 EPA and DHA.",
    ingredients: ["1 whole-grain bagel thin", "2 tbsp whipped cream cheese", "2 oz smoked salmon", "2 slices tomato", "1 tbsp capers", "1 tbsp sliced red onion", "Fresh dill"],
    instructions: ["Toast bagel halves until golden.", "Spread cream cheese on each half.", "Layer salmon, tomato, capers, and red onion.", "Finish with fresh dill."],
  },
  {
    id: "tofuscramble",
    cat: "breakfast",
    emoji: "🌿",
    title: "Savory Tofu Scramble",
    time: "10 min",
    calories: "250 cal",
    summary: "A plant-based alternative to scrambled eggs, just as satisfying.",
    benefit: "Tofu is a soy-based protein that has been linked in studies to supporting healthy cholesterol.",
    ingredients: ["1/2 block firm tofu, crumbled", "1/2 tsp turmeric", "1/2 tsp garlic powder", "1 cup spinach", "1/4 cup diced pepper", "1 tbsp olive oil", "Salt and pepper"],
    instructions: ["Heat olive oil in a skillet over medium heat.", "Add pepper; cook 2 min.", "Add tofu, turmeric, and garlic powder; cook 4 min stirring.", "Stir in spinach until wilted. Season and serve."],
  },
  {
    id: "buckwheat",
    cat: "breakfast",
    emoji: "🌾",
    title: "Buckwheat Porridge with Berries",
    time: "20 min",
    calories: "300 cal",
    summary: "A naturally gluten-free, fiber-packed warm breakfast.",
    benefit: "Buckwheat contains rutin, a flavonoid studied for its support of healthy blood vessels.",
    ingredients: ["1/3 cup buckwheat groats", "1 cup water", "1/2 cup almond milk", "1/4 cup strawberries", "1 tbsp chopped almonds", "1 tsp maple syrup"],
    instructions: ["Rinse buckwheat. Simmer in water 15 min until tender.", "Stir in almond milk and maple syrup.", "Top with berries and almonds."],
  },
  {
    id: "banananuts",
    cat: "breakfast",
    emoji: "🍌",
    title: "Banana Walnut Mini Muffins",
    time: "25 min",
    calories: "150 cal (2 muffins)",
    summary: "Lightly sweet muffins made with whole-wheat flour and walnuts.",
    benefit: "Walnuts are the only nut with a meaningful amount of plant-based omega-3s — a heart-health all-star.",
    ingredients: ["1 cup whole-wheat flour", "1 tsp baking powder", "2 ripe bananas, mashed", "1 egg", "2 tbsp olive oil", "2 tbsp maple syrup", "1/3 cup chopped walnuts"],
    instructions: ["Preheat oven to 350°F (175°C).", "Mix bananas, egg, oil, and syrup.", "Fold in flour, baking powder, and walnuts.", "Spoon into a greased mini muffin tin.", "Bake 15-18 min until golden."],
  },
  {
    id: "veggieburrito",
    cat: "breakfast",
    emoji: "🌯",
    title: "Veggie Breakfast Burrito",
    time: "12 min",
    calories: "370 cal",
    summary: "Whole-wheat wrap stuffed with eggs, beans, and peppers.",
    benefit: "Black beans deliver fiber and plant protein that help keep cholesterol in check.",
    ingredients: ["1 whole-wheat tortilla", "2 eggs", "1/4 cup black beans, rinsed", "1/4 cup diced peppers", "2 tbsp salsa", "1 tbsp sliced avocado", "Cilantro"],
    instructions: ["Scramble eggs in a nonstick pan.", "Warm black beans and peppers briefly.", "Warm tortilla 20 sec.", "Fill with eggs, beans, peppers, avocado, salsa, cilantro.", "Fold ends and roll tightly."],
  },
  {
    id: "almondbanana",
    cat: "breakfast",
    emoji: "🍞",
    title: "Almond Butter Banana Toast",
    time: "3 min",
    calories: "310 cal",
    summary: "Whole-grain toast topped with almond butter, banana, and a drizzle of honey.",
    benefit: "Almond butter brings vitamin E and healthy fats that work alongside HealthyBlood.",
    ingredients: ["1 slice whole-grain bread", "2 tbsp almond butter", "1/2 banana, sliced", "1 tsp honey", "Pinch of cinnamon", "Chia seeds"],
    instructions: ["Toast bread.", "Spread with almond butter.", "Top with banana slices, cinnamon, honey, and chia seeds."],
  },
  {
    id: "frittata",
    cat: "breakfast",
    emoji: "🥬",
    title: "Spinach Mushroom Frittata",
    time: "25 min",
    calories: "220 cal",
    summary: "An oven-baked frittata — great hot or as make-ahead meal prep.",
    benefit: "Mushrooms are the only plant source of vitamin D and deliver heart-supporting potassium.",
    ingredients: ["6 eggs", "1 cup spinach", "1 cup sliced mushrooms", "1/4 cup feta", "1 tbsp olive oil", "1/4 tsp black pepper"],
    instructions: ["Preheat oven to 375°F (190°C).", "Sauté mushrooms in olive oil 5 min in an oven-safe pan.", "Add spinach until wilted.", "Beat eggs with pepper; pour over veggies.", "Sprinkle feta. Bake 15 min until set."],
  },
  {
    id: "cottagecheese",
    cat: "breakfast",
    emoji: "🍍",
    title: "Cottage Cheese Tropical Bowl",
    time: "3 min",
    calories: "250 cal",
    summary: "A protein-packed bowl with pineapple, flax, and a touch of honey.",
    benefit: "Low-fat cottage cheese is a lean protein; pineapple brings bromelain and vitamin C.",
    ingredients: ["3/4 cup low-fat cottage cheese", "1/2 cup fresh pineapple", "1 tbsp ground flaxseed", "2 tbsp sliced almonds", "1 tsp honey"],
    instructions: ["Spoon cottage cheese into a bowl.", "Top with pineapple, flax, almonds, and honey."],
  },
  {
    id: "pumpkinbowl",
    cat: "breakfast",
    emoji: "🎃",
    title: "Pumpkin Spice Smoothie Bowl",
    time: "5 min",
    calories: "290 cal",
    summary: "A thick, spoonable smoothie bowl with pumpkin, oats, and warming spices.",
    benefit: "Pumpkin is loaded with beta-carotene and potassium, both of which support vascular health.",
    ingredients: ["1/2 cup pumpkin puree", "1/2 frozen banana", "1/4 cup rolled oats", "1/2 cup almond milk", "1/2 tsp pumpkin pie spice", "1 tbsp pepitas", "1 tsp maple syrup"],
    instructions: ["Blend pumpkin, banana, oats, milk, and spice until thick.", "Pour into a bowl.", "Top with pepitas and maple syrup."],
  },
  {
    id: "ricottatoast",
    cat: "breakfast",
    emoji: "🍯",
    title: "Ricotta Honey Fig Toast",
    time: "5 min",
    calories: "310 cal",
    summary: "A lightly sweet breakfast with creamy ricotta and fresh figs.",
    benefit: "Figs offer fiber and potassium; whole grains keep blood sugar stable.",
    ingredients: ["1 slice whole-grain sourdough", "3 tbsp part-skim ricotta", "2 fresh figs, sliced", "1 tsp honey", "Pinch of cinnamon", "1 tbsp chopped pistachios"],
    instructions: ["Toast bread.", "Spread ricotta over toast.", "Top with figs, pistachios, honey, and cinnamon."],
  },

  // ================================================
  // LUNCH
  // ================================================
  {
    id: "buddha",
    cat: "lunch",
    emoji: "🥗",
    title: "Mediterranean Buddha Bowl",
    time: "15 min",
    calories: "420 cal",
    summary: "A colorful bowl of leafy greens, chickpeas, and olive oil.",
    benefit: "Loaded with fiber, plant protein, and monounsaturated fats — the foundation of the Mediterranean diet linked to better heart health.",
    ingredients: ["2 cups baby spinach", "1/2 cup cooked quinoa", "1/2 cup chickpeas, drained", "1/4 cucumber, diced", "1/4 cup cherry tomatoes", "2 tbsp hummus", "1 tbsp olive oil", "Squeeze of lemon"],
    instructions: ["Layer spinach in a bowl as the base.", "Top with quinoa, chickpeas, cucumber, and tomatoes.", "Add a generous spoonful of hummus.", "Drizzle with olive oil and lemon juice.", "Toss gently and enjoy."],
  },
  {
    id: "tunasalad",
    cat: "lunch",
    emoji: "🥪",
    title: "Tuna Salad on Whole Grain",
    time: "8 min",
    calories: "360 cal",
    summary: "Classic tuna salad made with olive oil and Greek yogurt instead of mayo.",
    benefit: "Tuna delivers lean protein and omega-3s. Swapping mayo for yogurt saves saturated fat.",
    ingredients: ["1 can (5 oz) tuna in water, drained", "2 tbsp plain Greek yogurt", "1 tsp olive oil", "1 tbsp diced celery", "1 tbsp diced red onion", "1 tsp Dijon mustard", "2 slices whole-grain bread", "Lettuce leaf"],
    instructions: ["Mix tuna, yogurt, oil, celery, onion, and mustard.", "Toast bread if desired.", "Layer lettuce and tuna salad on bread. Top with second slice."],
  },
  {
    id: "turkeywrap",
    cat: "lunch",
    emoji: "🌯",
    title: "Turkey Avocado Wrap",
    time: "5 min",
    calories: "390 cal",
    summary: "A grab-and-go lunch with lean turkey, avocado, and crunchy veggies.",
    benefit: "Lean turkey is a low-saturated-fat protein; avocado adds the good fats your heart wants.",
    ingredients: ["1 whole-wheat tortilla", "3 oz sliced deli turkey (low sodium)", "1/4 avocado, sliced", "1/4 cup shredded lettuce", "1 tbsp hummus", "2 slices tomato", "1 tbsp sliced red onion"],
    instructions: ["Spread hummus on tortilla.", "Layer turkey, avocado, lettuce, tomato, onion.", "Fold sides and roll tightly. Cut in half."],
  },
  {
    id: "lentilsalad",
    cat: "lunch",
    emoji: "🫘",
    title: "Lentil Salad with Feta",
    time: "15 min",
    calories: "380 cal",
    summary: "A protein-rich lentil salad with fresh herbs and crumbled feta.",
    benefit: "Lentils are one of the most fiber-dense foods you can eat and are strongly linked to supporting healthy cholesterol.",
    ingredients: ["1 cup cooked green lentils", "1/4 cup diced cucumber", "1/4 cup cherry tomatoes, halved", "2 tbsp crumbled feta", "2 tbsp chopped parsley", "1 tbsp olive oil", "1 tbsp lemon juice", "Salt and pepper"],
    instructions: ["Whisk olive oil, lemon, salt, and pepper.", "Combine lentils, cucumber, tomatoes, feta, parsley in a bowl.", "Toss with dressing and serve."],
  },
  {
    id: "chickpeasw",
    cat: "lunch",
    emoji: "🥖",
    title: "Smashed Chickpea Sandwich",
    time: "8 min",
    calories: "360 cal",
    summary: "A plant-based alternative to tuna salad, made with chickpeas and herbs.",
    benefit: "Chickpeas deliver soluble fiber and plant protein, both of which help maintain healthy cholesterol.",
    ingredients: ["1 cup chickpeas, drained", "2 tbsp plain Greek yogurt", "1 tbsp Dijon", "1 tbsp chopped celery", "1 tbsp chopped red onion", "1 tsp lemon juice", "2 slices whole-grain bread", "Lettuce and tomato"],
    instructions: ["Mash chickpeas with a fork, leaving some texture.", "Stir in yogurt, Dijon, celery, onion, and lemon.", "Pile onto bread with lettuce and tomato."],
  },
  {
    id: "tabbouleh",
    cat: "lunch",
    emoji: "🌿",
    title: "Quinoa Tabbouleh",
    time: "15 min",
    calories: "310 cal",
    summary: "A herby, lemony grain salad with tons of fresh parsley.",
    benefit: "Parsley is rich in vitamin K and flavonoids; quinoa adds complete plant protein.",
    ingredients: ["1 cup cooked quinoa", "1 cup chopped parsley", "1/4 cup chopped mint", "1/2 cup diced tomato", "1/4 cup diced cucumber", "2 tbsp olive oil", "2 tbsp lemon juice", "Salt"],
    instructions: ["Combine quinoa, parsley, mint, tomato, cucumber.", "Whisk olive oil, lemon, and salt.", "Toss and chill 10 min before serving."],
  },
  {
    id: "nicoise",
    cat: "lunch",
    emoji: "🥚",
    title: "Salmon Niçoise Salad",
    time: "15 min",
    calories: "440 cal",
    summary: "A classic French composed salad with salmon, eggs, and green beans.",
    benefit: "Combines omega-3 rich salmon with olive oil dressing — a Mediterranean diet hallmark.",
    ingredients: ["4 oz cooked salmon", "2 cups mixed greens", "1/2 cup cooked green beans", "1 hard-boiled egg, quartered", "6 olives", "4 cherry tomatoes", "1 tbsp olive oil", "1 tbsp red wine vinegar", "1 tsp Dijon"],
    instructions: ["Arrange greens on a plate.", "Top with salmon, beans, egg, olives, tomatoes in groups.", "Whisk olive oil, vinegar, Dijon. Drizzle over salad."],
  },
  {
    id: "pastasalad",
    cat: "lunch",
    emoji: "🍝",
    title: "Mediterranean Pasta Salad",
    time: "15 min",
    calories: "380 cal",
    summary: "Whole-wheat pasta tossed with olives, tomatoes, and herbs.",
    benefit: "Whole-wheat pasta keeps fiber intact. Olive oil and olives deliver monounsaturated fats.",
    ingredients: ["1 cup cooked whole-wheat pasta", "1/2 cup cherry tomatoes", "1/4 cup olives", "1/4 cup diced cucumber", "2 tbsp feta", "1 tbsp olive oil", "1 tbsp lemon juice", "Basil"],
    instructions: ["Cool cooked pasta under running water.", "Toss with all ingredients.", "Chill 10 min before serving."],
  },
  {
    id: "hummuswrap",
    cat: "lunch",
    emoji: "🌯",
    title: "Veggie Hummus Wrap",
    time: "5 min",
    calories: "340 cal",
    summary: "A plant-powered wrap stuffed with hummus, greens, and crunchy veggies.",
    benefit: "Hummus brings chickpeas' fiber and tahini's healthy fats in one creamy spread.",
    ingredients: ["1 whole-wheat tortilla", "3 tbsp hummus", "1/4 cup shredded carrot", "1/4 cucumber, sliced", "1/4 cup baby spinach", "2 slices tomato", "2 tbsp sprouts"],
    instructions: ["Spread hummus on tortilla.", "Layer all vegetables.", "Roll tightly and slice in half."],
  },
  {
    id: "blackbeanbowl",
    cat: "lunch",
    emoji: "🌮",
    title: "Black Bean Burrito Bowl",
    time: "12 min",
    calories: "420 cal",
    summary: "A lighter burrito bowl skipping the tortilla and rice-heavy version.",
    benefit: "Black beans and brown rice together make a complete plant protein with plenty of fiber.",
    ingredients: ["1/2 cup cooked brown rice", "1/2 cup black beans", "1/4 cup corn", "1/4 cup salsa", "2 tbsp avocado", "1 tbsp plain yogurt", "Lime wedge", "Cilantro"],
    instructions: ["Layer rice, beans, corn, salsa in a bowl.", "Top with avocado, yogurt, cilantro, and a lime squeeze."],
  },
  {
    id: "roastedveggiebowl",
    cat: "lunch",
    emoji: "🍠",
    title: "Roasted Vegetable Grain Bowl",
    time: "30 min",
    calories: "420 cal",
    summary: "Farro topped with a rainbow of oven-roasted veggies.",
    benefit: "Farro is a whole grain full of fiber; roasting veggies concentrates their flavor without added sugars.",
    ingredients: ["1/2 cup cooked farro", "1/2 cup butternut squash cubes", "1/2 cup brussels sprouts, halved", "1/4 red onion, wedged", "1 tbsp olive oil", "2 tbsp tahini", "1 tbsp lemon juice", "Salt and pepper"],
    instructions: ["Preheat oven to 425°F.", "Toss veggies with olive oil, salt, pepper.", "Roast 20 min.", "Whisk tahini and lemon.", "Serve veggies over farro; drizzle tahini sauce."],
  },
  {
    id: "lettucewraps",
    cat: "lunch",
    emoji: "🥬",
    title: "Asian Chicken Lettuce Wraps",
    time: "15 min",
    calories: "310 cal",
    summary: "Lean ground chicken and veggies tucked into crisp lettuce cups.",
    benefit: "Lean poultry with lots of vegetables keeps calories low and nutrients high.",
    ingredients: ["4 oz ground chicken breast", "1/4 cup diced water chestnuts", "1/4 cup diced mushrooms", "2 green onions, sliced", "1 tbsp low-sodium soy sauce", "1 tsp grated ginger", "1 tsp sesame oil", "4 butter lettuce leaves"],
    instructions: ["Heat sesame oil in a pan. Cook chicken until browned.", "Add mushrooms, water chestnuts, ginger, soy. Cook 3 min.", "Spoon into lettuce leaves. Top with green onion."],
  },
  {
    id: "caprese",
    cat: "lunch",
    emoji: "🍅",
    title: "Caprese Sandwich",
    time: "5 min",
    calories: "360 cal",
    summary: "Fresh mozzarella, tomato, and basil on crusty whole-grain bread.",
    benefit: "Tomatoes deliver lycopene; olive oil brings heart-healthy fats — classic Italian simplicity.",
    ingredients: ["2 slices whole-grain ciabatta", "2 oz fresh mozzarella, sliced", "1 large tomato, sliced", "4 fresh basil leaves", "1 tbsp olive oil", "1 tsp balsamic vinegar", "Salt and pepper"],
    instructions: ["Drizzle bread with olive oil.", "Layer mozzarella, tomato, basil.", "Drizzle balsamic; season and close sandwich."],
  },
  {
    id: "greekpita",
    cat: "lunch",
    emoji: "🥙",
    title: "Greek Pita Pocket",
    time: "8 min",
    calories: "380 cal",
    summary: "Whole-wheat pita stuffed with Greek salad fixings and grilled chicken.",
    benefit: "A balanced meal with veggies, lean protein, and whole grains in one portable package.",
    ingredients: ["1 whole-wheat pita", "3 oz grilled chicken", "1/4 cup shredded lettuce", "1/4 cup diced tomato", "2 tbsp tzatziki", "1 tbsp crumbled feta", "2 olives"],
    instructions: ["Warm pita and cut open.", "Stuff with lettuce, tomato, chicken, olives.", "Drizzle tzatziki and sprinkle feta."],
  },
  {
    id: "veggiepanini",
    cat: "lunch",
    emoji: "🥪",
    title: "Grilled Veggie Panini",
    time: "12 min",
    calories: "390 cal",
    summary: "A warm pressed sandwich loaded with roasted peppers and zucchini.",
    benefit: "Roasted vegetables with olive oil pack in antioxidants and monounsaturated fats.",
    ingredients: ["2 slices whole-grain bread", "2 tbsp hummus", "4 slices roasted zucchini", "4 slices roasted red pepper", "1 oz fresh mozzarella", "Basil leaves", "1 tsp olive oil"],
    instructions: ["Spread hummus on bread.", "Layer veggies, mozzarella, basil.", "Brush outside with olive oil.", "Press in a pan 3-4 min per side until toasted."],
  },
  {
    id: "salmonsalad",
    cat: "lunch",
    emoji: "🐟",
    title: "Smoked Salmon Salad",
    time: "8 min",
    calories: "340 cal",
    summary: "A simple salad that turns smoked salmon into a full meal.",
    benefit: "Smoked salmon provides high-quality omega-3s with every bite.",
    ingredients: ["3 oz smoked salmon", "2 cups arugula", "1/4 avocado, sliced", "1 tbsp capers", "1/4 cup cucumber", "1 tbsp olive oil", "1 tbsp lemon juice", "Dill"],
    instructions: ["Arrange arugula on a plate.", "Top with salmon, avocado, cucumber, capers.", "Whisk oil and lemon; drizzle on top.", "Finish with fresh dill."],
  },
  {
    id: "edamamebowl",
    cat: "lunch",
    emoji: "🌱",
    title: "Edamame Quinoa Bowl",
    time: "15 min",
    calories: "400 cal",
    summary: "A plant-protein-packed bowl with quinoa, edamame, and sesame dressing.",
    benefit: "Edamame (young soybeans) offers complete protein and isoflavones linked to heart health.",
    ingredients: ["1/2 cup cooked quinoa", "1/2 cup shelled edamame", "1/4 cup shredded carrot", "1/4 cup cucumber", "1 tbsp sesame seeds", "1 tbsp low-sodium soy sauce", "1 tsp sesame oil", "1 tsp rice vinegar"],
    instructions: ["Whisk soy, sesame oil, vinegar.", "Layer quinoa, edamame, carrot, cucumber.", "Drizzle dressing and sprinkle sesame seeds."],
  },
  {
    id: "curriedchickpea",
    cat: "lunch",
    emoji: "🧆",
    title: "Curried Chickpea Wrap",
    time: "10 min",
    calories: "360 cal",
    summary: "A creamy, slightly sweet curried chickpea salad wrapped in flatbread.",
    benefit: "Chickpeas bring fiber and plant protein; turmeric adds anti-inflammatory compounds.",
    ingredients: ["1 cup chickpeas, mashed", "2 tbsp plain Greek yogurt", "1 tsp curry powder", "1 tbsp raisins", "1 tbsp chopped almonds", "1 whole-wheat wrap", "1/4 cup baby spinach"],
    instructions: ["Mix chickpeas, yogurt, curry, raisins, almonds.", "Spread over wrap.", "Top with spinach and roll."],
  },
  {
    id: "falafelbowl",
    cat: "lunch",
    emoji: "🧆",
    title: "Falafel Bowl",
    time: "20 min",
    calories: "440 cal",
    summary: "Baked falafel over greens with tahini dressing.",
    benefit: "Baked (not fried) falafel keeps chickpea's heart benefits without added saturated fat.",
    ingredients: ["4 baked falafel balls", "2 cups mixed greens", "1/4 cup cucumber", "1/4 cup tomato", "2 tbsp tahini", "1 tbsp lemon juice", "2 tbsp water", "1 tbsp olive oil"],
    instructions: ["Whisk tahini, lemon, water, oil.", "Arrange greens, cucumber, tomato in bowl.", "Top with falafel and drizzle tahini dressing."],
  },
  {
    id: "whitebeantuna",
    cat: "lunch",
    emoji: "🫛",
    title: "White Bean & Tuna Salad",
    time: "10 min",
    calories: "380 cal",
    summary: "An Italian-style bean salad with tuna, red onion, and lemon.",
    benefit: "White beans are rich in potassium and fiber; tuna adds omega-3s.",
    ingredients: ["1 can (5 oz) tuna in water", "1 cup canned white beans, rinsed", "2 tbsp sliced red onion", "2 tbsp chopped parsley", "2 tbsp olive oil", "1 tbsp lemon juice", "Salt and pepper"],
    instructions: ["Flake tuna in a bowl.", "Add beans, onion, parsley.", "Drizzle olive oil and lemon; toss gently."],
  },
  {
    id: "grilledchickcaesar",
    cat: "lunch",
    emoji: "🥗",
    title: "Light Grilled Chicken Caesar",
    time: "15 min",
    calories: "380 cal",
    summary: "A lighter Caesar made with Greek yogurt dressing.",
    benefit: "Greek yogurt dressing slashes saturated fat while keeping the creamy texture.",
    ingredients: ["4 oz grilled chicken breast", "3 cups romaine, chopped", "2 tbsp Greek yogurt", "1 tsp Dijon", "1 tsp anchovy paste (optional)", "1 tbsp lemon juice", "1 tbsp Parmesan", "1 tbsp whole-grain croutons"],
    instructions: ["Whisk yogurt, Dijon, anchovy, lemon.", "Toss romaine with dressing.", "Top with chicken, Parmesan, and croutons."],
  },

  // ================================================
  // DINNER
  // ================================================
  {
    id: "salmon",
    cat: "dinner",
    emoji: "🐟",
    title: "Lemon Garlic Salmon",
    time: "20 min",
    calories: "380 cal",
    summary: "Omega-3 rich salmon paired with heart-healthy olive oil and garlic.",
    benefit: "Salmon's omega-3 fatty acids support healthy triglycerides. Garlic adds cardiovascular benefits that pair beautifully with HealthyBlood.",
    ingredients: ["1 salmon fillet (5 oz)", "2 tbsp olive oil", "2 cloves garlic, minced", "1 lemon (juice + zest)", "1 tsp dried oregano", "Salt and pepper", "Fresh parsley"],
    instructions: ["Preheat oven to 400°F (200°C).", "Whisk olive oil, garlic, lemon, oregano.", "Brush salmon with mixture.", "Bake 12-15 min until flaky.", "Garnish with parsley."],
  },
  {
    id: "bakedcod",
    cat: "dinner",
    emoji: "🐠",
    title: "Baked Cod with Herbs",
    time: "20 min",
    calories: "300 cal",
    summary: "Flaky white fish with a fresh herb and olive oil topping.",
    benefit: "Cod is a very lean protein. When baked with olive oil and herbs, it becomes a heart-smart Mediterranean classic.",
    ingredients: ["1 cod fillet (5 oz)", "2 tbsp olive oil", "2 tbsp chopped parsley", "1 tbsp chopped dill", "1 clove garlic, minced", "1 lemon, sliced", "Salt and pepper"],
    instructions: ["Preheat oven to 400°F.", "Mix olive oil, herbs, garlic.", "Place cod in a baking dish. Top with herb mixture.", "Lay lemon slices over.", "Bake 12-14 min until flaky."],
  },
  {
    id: "chicktapenade",
    cat: "dinner",
    emoji: "🫒",
    title: "Grilled Chicken with Olive Tapenade",
    time: "25 min",
    calories: "420 cal",
    summary: "Lean chicken breast topped with briny olive tapenade.",
    benefit: "Olives bring heart-friendly monounsaturated fats and antioxidants from their polyphenols.",
    ingredients: ["1 boneless skinless chicken breast", "1/2 cup pitted mixed olives", "1 tbsp capers", "2 cloves garlic", "2 tbsp olive oil", "1 tbsp lemon juice", "Fresh basil"],
    instructions: ["Pulse olives, capers, garlic, olive oil, lemon into a rough paste.", "Season chicken with salt and pepper.", "Grill 6 min per side until cooked through.", "Top with tapenade and basil."],
  },
  {
    id: "stuffedpeppers",
    cat: "dinner",
    emoji: "🫑",
    title: "Turkey Stuffed Bell Peppers",
    time: "40 min",
    calories: "400 cal",
    summary: "Bell peppers filled with ground turkey, brown rice, and tomatoes.",
    benefit: "Lean turkey instead of beef cuts saturated fat dramatically. Peppers add vitamin C for vascular health.",
    ingredients: ["4 bell peppers, tops cut off", "1 lb lean ground turkey", "1 cup cooked brown rice", "1 can diced tomatoes", "1/2 onion, diced", "2 cloves garlic, minced", "1 tbsp olive oil", "1 tsp Italian seasoning"],
    instructions: ["Preheat oven to 375°F.", "Sauté onion and garlic in olive oil 3 min.", "Add turkey; cook until browned.", "Stir in rice, tomatoes, seasoning.", "Stuff peppers and place upright in a dish.", "Bake 30 min until tender."],
  },
  {
    id: "tofustirfry",
    cat: "dinner",
    emoji: "🥦",
    title: "Vegetable Stir Fry with Tofu",
    time: "15 min",
    calories: "390 cal",
    summary: "A colorful stir fry packed with tofu, broccoli, and snap peas.",
    benefit: "Tofu delivers soy protein linked to healthy cholesterol; the rainbow of veggies adds fiber and phytonutrients.",
    ingredients: ["1/2 block firm tofu, cubed", "1 cup broccoli florets", "1/2 cup snap peas", "1/2 cup sliced peppers", "2 tbsp low-sodium soy sauce", "1 tsp grated ginger", "1 clove garlic", "1 tbsp sesame oil", "1/2 cup cooked brown rice"],
    instructions: ["Heat sesame oil in a wok.", "Stir-fry tofu 4 min until golden.", "Add veggies, ginger, garlic. Stir-fry 5 min.", "Add soy sauce. Toss to coat.", "Serve over brown rice."],
  },
  {
    id: "medchicken",
    cat: "dinner",
    emoji: "🍋",
    title: "Mediterranean Baked Chicken",
    time: "35 min",
    calories: "420 cal",
    summary: "Chicken baked with tomatoes, olives, and artichokes.",
    benefit: "A classic Mediterranean combination — lean protein plus vegetables in olive oil.",
    ingredients: ["4 chicken thighs, skin removed", "1 cup cherry tomatoes", "1/2 cup kalamata olives", "1/2 cup artichoke hearts", "3 cloves garlic", "2 tbsp olive oil", "1 tbsp oregano", "1 lemon"],
    instructions: ["Preheat oven to 400°F.", "Place chicken in a baking dish.", "Scatter tomatoes, olives, artichokes, garlic around.", "Drizzle olive oil, oregano, lemon juice.", "Bake 25-30 min."],
  },
  {
    id: "salmonasparagus",
    cat: "dinner",
    emoji: "🥬",
    title: "Baked Salmon with Asparagus",
    time: "20 min",
    calories: "410 cal",
    summary: "A simple sheet pan dinner with salmon and roasted asparagus.",
    benefit: "Omega-3 rich salmon plus folate-rich asparagus makes a vascular-health power duo.",
    ingredients: ["1 salmon fillet (5 oz)", "1 bunch asparagus, trimmed", "2 tbsp olive oil", "1 clove garlic, minced", "1 lemon, sliced", "Salt and pepper"],
    instructions: ["Preheat oven to 425°F.", "Toss asparagus with olive oil, garlic, salt.", "Place salmon on same sheet pan.", "Top salmon with lemon slices.", "Bake 12-14 min."],
  },
  {
    id: "pastaprimavera",
    cat: "dinner",
    emoji: "🍝",
    title: "Whole Wheat Pasta Primavera",
    time: "20 min",
    calories: "420 cal",
    summary: "Whole wheat pasta tossed with a rainbow of sautéed vegetables.",
    benefit: "Whole-grain pasta keeps the fiber intact while sautéed veggies add antioxidants and volume.",
    ingredients: ["1 cup whole-wheat penne", "1 cup broccoli florets", "1/2 cup sliced zucchini", "1/2 cup cherry tomatoes", "2 cloves garlic", "3 tbsp olive oil", "2 tbsp Parmesan", "Fresh basil"],
    instructions: ["Cook pasta per package directions.", "Sauté garlic in olive oil.", "Add broccoli, zucchini; cook 5 min.", "Add tomatoes; cook 2 min.", "Toss with pasta. Finish with Parmesan and basil."],
  },
  {
    id: "turkeychili",
    cat: "dinner",
    emoji: "🌶",
    title: "Lean Turkey Chili",
    time: "40 min",
    calories: "390 cal",
    summary: "A smoky, hearty chili made with lean turkey and three beans.",
    benefit: "Swapping beef for turkey cuts saturated fat; beans add serious fiber and plant protein.",
    ingredients: ["1 lb lean ground turkey", "1 can kidney beans", "1 can black beans", "1 can diced tomatoes", "1 onion, diced", "2 tbsp chili powder", "1 tsp cumin", "1 tbsp olive oil"],
    instructions: ["Sauté onion in olive oil 3 min.", "Add turkey; cook until browned.", "Add tomatoes, beans, spices.", "Simmer covered 25 min.", "Taste and adjust seasoning."],
  },
  {
    id: "eggplantparm",
    cat: "dinner",
    emoji: "🍆",
    title: "Baked Eggplant Parmesan",
    time: "45 min",
    calories: "390 cal",
    summary: "Oven-baked eggplant layered with marinara and part-skim mozzarella.",
    benefit: "Baking instead of frying slashes saturated fat while eggplant brings fiber and potassium.",
    ingredients: ["1 eggplant, sliced 1/2 inch", "1 egg, beaten", "1/2 cup whole-wheat breadcrumbs", "1 cup marinara", "1/2 cup part-skim mozzarella", "2 tbsp Parmesan", "1 tbsp olive oil"],
    instructions: ["Preheat oven to 400°F.", "Dip eggplant in egg, then breadcrumbs.", "Place on oiled sheet. Bake 20 min flipping once.", "Layer with marinara and cheese.", "Bake 10 more min until bubbly."],
  },
  {
    id: "veggiecurry",
    cat: "dinner",
    emoji: "🍛",
    title: "Veggie Curry with Brown Rice",
    time: "30 min",
    calories: "420 cal",
    summary: "A fragrant coconut-based curry with cauliflower, peas, and spinach.",
    benefit: "Turmeric in curry offers anti-inflammatory curcumin, while brown rice keeps fiber intact.",
    ingredients: ["2 cups cauliflower florets", "1 cup peas", "2 cups spinach", "1 can light coconut milk", "2 tbsp curry paste", "1 onion, diced", "1 tbsp olive oil", "1/2 cup brown rice, cooked"],
    instructions: ["Sauté onion in oil 3 min.", "Add curry paste; cook 1 min.", "Add cauliflower, peas, coconut milk. Simmer 15 min.", "Stir in spinach until wilted.", "Serve over brown rice."],
  },
  {
    id: "portobello",
    cat: "dinner",
    emoji: "🍄",
    title: "Stuffed Portobello Mushrooms",
    time: "30 min",
    calories: "310 cal",
    summary: "Giant portobellos filled with spinach, tomato, and quinoa.",
    benefit: "Mushrooms deliver potassium and beta-glucans that support heart health.",
    ingredients: ["4 portobello caps, gills removed", "1/2 cup cooked quinoa", "1 cup spinach, chopped", "1/4 cup diced tomato", "2 tbsp crumbled feta", "2 tbsp olive oil", "1 clove garlic"],
    instructions: ["Preheat oven to 400°F.", "Brush mushrooms with oil.", "Mix quinoa, spinach, tomato, feta, garlic.", "Spoon filling into caps.", "Bake 20 min."],
  },
  {
    id: "searedtuna",
    cat: "dinner",
    emoji: "🍣",
    title: "Seared Tuna over Greens",
    time: "12 min",
    calories: "380 cal",
    summary: "Sesame-crusted tuna seared rare over a bed of arugula.",
    benefit: "Tuna is a lean source of omega-3s; arugula adds vitamin K and nitrates for blood vessel health.",
    ingredients: ["1 tuna steak (5 oz)", "2 tbsp sesame seeds", "2 cups arugula", "1 tbsp olive oil", "1 tbsp low-sodium soy sauce", "1 tsp sesame oil", "1 tsp rice vinegar"],
    instructions: ["Press sesame seeds onto tuna.", "Sear in hot olive oil 90 sec per side for rare.", "Slice thinly.", "Whisk soy, sesame oil, vinegar.", "Arrange tuna over arugula; drizzle dressing."],
  },
  {
    id: "cacciatore",
    cat: "dinner",
    emoji: "🍅",
    title: "Chicken Cacciatore",
    time: "45 min",
    calories: "410 cal",
    summary: "A rustic Italian chicken stew with tomatoes, peppers, and olives.",
    benefit: "Slow-simmered tomatoes release lycopene — a powerful heart-healthy antioxidant.",
    ingredients: ["4 chicken thighs, skinless", "1 can crushed tomatoes", "1 bell pepper, sliced", "1/2 cup olives", "1 onion, sliced", "3 cloves garlic", "2 tbsp olive oil", "1 tsp oregano"],
    instructions: ["Brown chicken in olive oil 4 min per side; remove.", "Sauté onion, pepper, garlic 5 min.", "Add tomatoes, olives, oregano.", "Return chicken. Simmer covered 30 min."],
  },
  {
    id: "salmonburgers",
    cat: "dinner",
    emoji: "🍔",
    title: "Salmon Burgers",
    time: "20 min",
    calories: "400 cal",
    summary: "Homemade salmon patties on whole-grain buns with avocado.",
    benefit: "Getting salmon in burger form is a tasty way to boost omega-3 intake.",
    ingredients: ["1 lb salmon, finely chopped", "1 egg", "1/4 cup breadcrumbs", "2 tbsp chopped dill", "1 tbsp Dijon", "1 tbsp olive oil", "4 whole-grain buns", "Avocado slices"],
    instructions: ["Mix salmon, egg, breadcrumbs, dill, Dijon.", "Form into 4 patties.", "Cook in olive oil 4 min per side.", "Serve on buns with avocado."],
  },
  {
    id: "bbtacos",
    cat: "dinner",
    emoji: "🌮",
    title: "Black Bean Tacos",
    time: "15 min",
    calories: "380 cal",
    summary: "Vegetarian tacos with seasoned black beans and fresh toppings.",
    benefit: "Black beans are fiber champions. Corn tortillas are lower in calories than flour and gluten-free.",
    ingredients: ["1 can black beans, drained", "1 tsp cumin", "1 tsp chili powder", "6 small corn tortillas", "1/2 cup shredded cabbage", "1/4 cup salsa", "1/4 cup diced avocado", "Lime wedges"],
    instructions: ["Warm beans with cumin and chili powder 5 min.", "Warm tortillas.", "Fill with beans, cabbage, salsa, avocado.", "Squeeze lime on top."],
  },
  {
    id: "shrimpscampi",
    cat: "dinner",
    emoji: "🦐",
    title: "Light Shrimp Scampi",
    time: "15 min",
    calories: "380 cal",
    summary: "Garlicky shrimp in a light olive oil sauce over whole-wheat pasta.",
    benefit: "Shrimp is a low-calorie protein; using olive oil instead of butter keeps it heart-smart.",
    ingredients: ["12 large shrimp, peeled", "4 cloves garlic, minced", "3 tbsp olive oil", "1/4 cup white wine or broth", "2 tbsp lemon juice", "2 tbsp parsley", "1 cup cooked whole-wheat linguine"],
    instructions: ["Heat oil; sauté garlic 30 sec.", "Add shrimp; cook 2 min per side.", "Add wine, lemon juice; reduce 1 min.", "Toss with pasta and parsley."],
  },
  {
    id: "zucchiniboats",
    cat: "dinner",
    emoji: "🥒",
    title: "Stuffed Zucchini Boats",
    time: "35 min",
    calories: "360 cal",
    summary: "Zucchini halves filled with ground turkey, marinara, and herbs.",
    benefit: "Using zucchini as a 'boat' cuts calories while packing in fiber and water.",
    ingredients: ["2 large zucchini, halved and scooped", "1/2 lb ground turkey", "1/2 cup marinara", "1/4 cup chopped onion", "2 cloves garlic", "2 tbsp Parmesan", "1 tbsp olive oil"],
    instructions: ["Preheat oven to 400°F.", "Sauté onion, garlic, turkey in oil until browned.", "Stir in marinara.", "Spoon into zucchini halves.", "Sprinkle Parmesan. Bake 20 min."],
  },
  {
    id: "veglasagna",
    cat: "dinner",
    emoji: "🍝",
    title: "Vegetable Lasagna (light)",
    time: "1 hour",
    calories: "390 cal",
    summary: "Layered lasagna with spinach, zucchini, and part-skim ricotta.",
    benefit: "Loading lasagna with vegetables and using part-skim cheese makes it a heart-friendly comfort meal.",
    ingredients: ["6 whole-wheat lasagna noodles", "1 cup part-skim ricotta", "1 cup chopped spinach", "1 zucchini, sliced", "2 cups marinara", "1/2 cup shredded mozzarella", "2 tbsp Parmesan"],
    instructions: ["Preheat oven to 375°F.", "Cook noodles per package.", "Layer in dish: sauce, noodles, ricotta, spinach, zucchini. Repeat.", "Top with mozzarella and Parmesan.", "Bake 35 min; rest 10 min."],
  },
  {
    id: "tilapia",
    cat: "dinner",
    emoji: "🐟",
    title: "Mediterranean Baked Tilapia",
    time: "20 min",
    calories: "330 cal",
    summary: "Tilapia baked with tomatoes, olives, and capers.",
    benefit: "Tilapia is lean and quick-cooking; Mediterranean toppings add antioxidants.",
    ingredients: ["1 tilapia fillet (5 oz)", "1/2 cup cherry tomatoes", "2 tbsp olives", "1 tbsp capers", "2 tbsp olive oil", "1 clove garlic", "Lemon slices", "Oregano"],
    instructions: ["Preheat oven to 400°F.", "Place fish in baking dish.", "Top with tomatoes, olives, capers, garlic.", "Drizzle olive oil; add lemon slices.", "Bake 12 min."],
  },
  {
    id: "chickskewers",
    cat: "dinner",
    emoji: "🍗",
    title: "Lemon Herb Chicken Skewers",
    time: "25 min",
    calories: "380 cal",
    summary: "Grilled chicken skewers marinated in lemon, garlic, and herbs.",
    benefit: "Lean grilled chicken with herbs and olive oil is a Mediterranean staple.",
    ingredients: ["1 lb chicken breast, cubed", "3 tbsp olive oil", "2 tbsp lemon juice", "2 cloves garlic", "1 tbsp oregano", "1 tbsp parsley", "Skewers", "Salt and pepper"],
    instructions: ["Whisk marinade. Toss with chicken. Rest 15 min.", "Thread onto skewers.", "Grill 4-5 min per side."],
  },
  {
    id: "barleyrisotto",
    cat: "dinner",
    emoji: "🍚",
    title: "Mushroom Barley Risotto",
    time: "45 min",
    calories: "390 cal",
    summary: "A creamy risotto made with pearl barley instead of white rice.",
    benefit: "Barley contains beta-glucan, a soluble fiber specifically linked to supporting healthy cholesterol.",
    ingredients: ["1 cup pearl barley", "4 cups vegetable broth", "1 cup sliced mushrooms", "1/2 onion, diced", "2 cloves garlic", "2 tbsp olive oil", "2 tbsp Parmesan", "Fresh thyme"],
    instructions: ["Sauté onion, garlic, mushrooms in oil 5 min.", "Add barley; toast 1 min.", "Add broth 1/2 cup at a time, stirring until absorbed.", "Continue until barley is tender (about 30 min).", "Stir in Parmesan and thyme."],
  },
  {
    id: "salmontacos",
    cat: "dinner",
    emoji: "🌮",
    title: "Grilled Salmon Tacos",
    time: "20 min",
    calories: "400 cal",
    summary: "Grilled salmon in corn tortillas with cabbage slaw and lime.",
    benefit: "Salmon tacos let you enjoy a fun meal while still hitting your weekly omega-3 target.",
    ingredients: ["1 salmon fillet (5 oz)", "1 tbsp taco seasoning", "4 corn tortillas", "1 cup shredded cabbage", "2 tbsp Greek yogurt", "1 tbsp lime juice", "Cilantro"],
    instructions: ["Season salmon. Grill 4 min per side.", "Mix cabbage, yogurt, lime.", "Warm tortillas.", "Flake salmon into tortillas; top with slaw and cilantro."],
  },
  {
    id: "chickpeacurry",
    cat: "dinner",
    emoji: "🥘",
    title: "Chickpea Curry",
    time: "25 min",
    calories: "400 cal",
    summary: "A warming vegetarian curry with chickpeas and tomatoes.",
    benefit: "Combines the fiber of chickpeas with anti-inflammatory spices like turmeric and ginger.",
    ingredients: ["2 cans chickpeas, drained", "1 can diced tomatoes", "1 onion, diced", "2 cloves garlic", "1 tbsp ginger, grated", "2 tbsp curry powder", "1/2 cup light coconut milk", "2 tbsp olive oil"],
    instructions: ["Sauté onion, garlic, ginger in oil 4 min.", "Add curry powder; stir 1 min.", "Add tomatoes, chickpeas, coconut milk.", "Simmer 15 min."],
  },
  {
    id: "medsheetpan",
    cat: "dinner",
    emoji: "🫑",
    title: "Sheet Pan Mediterranean Veggies & Chicken",
    time: "35 min",
    calories: "420 cal",
    summary: "One-pan chicken with zucchini, peppers, tomatoes, and olives.",
    benefit: "Sheet pan meals keep olive oil and veggies front and center with minimal effort.",
    ingredients: ["1 chicken breast, cubed", "1 zucchini, sliced", "1 bell pepper, chunked", "1 cup cherry tomatoes", "1/2 cup olives", "3 tbsp olive oil", "1 tbsp oregano", "1 lemon"],
    instructions: ["Preheat oven to 425°F.", "Toss everything with olive oil, oregano, lemon juice, salt.", "Spread on a sheet pan.", "Roast 25 min until chicken is cooked through."],
  },

  // ================================================
  // SNACKS
  // ================================================
  {
    id: "hummusveggies",
    cat: "snacks",
    emoji: "🥕",
    title: "Hummus & Veggie Sticks",
    time: "3 min",
    calories: "180 cal",
    summary: "Crunchy carrots, cucumber, and peppers with creamy hummus.",
    benefit: "A classic combo — fiber-rich veggies paired with tahini and chickpea goodness.",
    ingredients: ["3 tbsp hummus", "1 carrot, cut into sticks", "1/2 cucumber, cut into sticks", "1/2 bell pepper, sliced"],
    instructions: ["Arrange veggies on a plate.", "Serve with hummus for dipping."],
  },
  {
    id: "almondsapple",
    cat: "snacks",
    emoji: "🍎",
    title: "Almonds & Apple",
    time: "1 min",
    calories: "220 cal",
    summary: "A perfectly simple snack: crunchy apple with a handful of raw almonds.",
    benefit: "Almonds deliver vitamin E and healthy fats; apples add soluble pectin fiber.",
    ingredients: ["1 medium apple", "1 oz raw almonds (about 22)"],
    instructions: ["Slice apple or eat whole.", "Enjoy with almonds."],
  },
  {
    id: "yogurthoney",
    cat: "snacks",
    emoji: "🍯",
    title: "Greek Yogurt with Honey & Walnuts",
    time: "2 min",
    calories: "220 cal",
    summary: "Thick Greek yogurt drizzled with honey and topped with walnuts.",
    benefit: "Protein-rich yogurt plus omega-3 walnuts equals a smart afternoon snack.",
    ingredients: ["3/4 cup plain 2% Greek yogurt", "1 tsp honey", "2 tbsp chopped walnuts", "Pinch of cinnamon"],
    instructions: ["Spoon yogurt into a bowl.", "Top with honey, walnuts, cinnamon."],
  },
  {
    id: "edamamesnack",
    cat: "snacks",
    emoji: "🫛",
    title: "Steamed Edamame",
    time: "5 min",
    calories: "170 cal",
    summary: "Warm edamame in the pod with a sprinkle of sea salt.",
    benefit: "Edamame is one of the only plant foods considered a complete protein.",
    ingredients: ["1 cup edamame in pods", "Pinch of sea salt"],
    instructions: ["Steam edamame 5 min.", "Sprinkle with salt.", "Squeeze pods to eat the beans."],
  },
  {
    id: "roastedchickpeas",
    cat: "snacks",
    emoji: "🌶",
    title: "Crispy Roasted Chickpeas",
    time: "30 min",
    calories: "160 cal",
    summary: "Crunchy, seasoned chickpeas — a fiber-rich alternative to chips.",
    benefit: "High in plant protein and fiber; way healthier than most packaged snacks.",
    ingredients: ["1 can chickpeas, drained and dried", "1 tbsp olive oil", "1 tsp paprika", "1/2 tsp cumin", "Salt"],
    instructions: ["Preheat oven to 400°F.", "Toss chickpeas with oil and spices.", "Spread on a sheet pan.", "Roast 25-30 min until crunchy."],
  },
  {
    id: "avocadocucumber",
    cat: "snacks",
    emoji: "🥒",
    title: "Avocado Cucumber Bites",
    time: "5 min",
    calories: "150 cal",
    summary: "Cool cucumber rounds topped with smashed avocado.",
    benefit: "Avocado's monounsaturated fats support healthy HDL; cucumber adds water and crunch.",
    ingredients: ["1/2 cucumber, sliced", "1/2 avocado, mashed", "1 tsp lime juice", "Pinch of salt", "Red pepper flakes"],
    instructions: ["Mix avocado, lime, salt.", "Top each cucumber slice with avocado.", "Finish with pepper flakes."],
  },
  {
    id: "trailmix",
    cat: "snacks",
    emoji: "🥜",
    title: "Homemade Trail Mix",
    time: "2 min",
    calories: "200 cal",
    summary: "A custom blend of nuts, seeds, and a touch of dark chocolate.",
    benefit: "DIY trail mix lets you control sugar and sodium while getting heart-healthy fats.",
    ingredients: ["2 tbsp raw almonds", "2 tbsp walnuts", "1 tbsp pumpkin seeds", "1 tbsp dried cranberries", "1 tbsp dark chocolate chips"],
    instructions: ["Combine all ingredients in a small bag or container."],
  },
  {
    id: "applealmond",
    cat: "snacks",
    emoji: "🍎",
    title: "Apple Slices with Almond Butter",
    time: "2 min",
    calories: "220 cal",
    summary: "Crisp apple slices with creamy almond butter for dipping.",
    benefit: "Soluble fiber from apples + healthy fats from almond butter keep you full for hours.",
    ingredients: ["1 apple, sliced", "2 tbsp almond butter", "Sprinkle of cinnamon"],
    instructions: ["Slice apple.", "Serve with almond butter and cinnamon."],
  },
  {
    id: "pepperhummus",
    cat: "snacks",
    emoji: "🫑",
    title: "Bell Pepper & Red Pepper Hummus",
    time: "3 min",
    calories: "160 cal",
    summary: "Sweet bell pepper strips with roasted red pepper hummus.",
    benefit: "Bell peppers have more vitamin C than oranges — key for blood vessel health.",
    ingredients: ["1 bell pepper, sliced", "3 tbsp roasted red pepper hummus"],
    instructions: ["Slice pepper.", "Serve with hummus for dipping."],
  },
  {
    id: "pumpkinseeds",
    cat: "snacks",
    emoji: "🎃",
    title: "Spiced Pumpkin Seeds",
    time: "20 min",
    calories: "170 cal",
    summary: "Toasted pumpkin seeds with a kick of smoked paprika.",
    benefit: "Pumpkin seeds (pepitas) are rich in magnesium, which supports healthy blood pressure.",
    ingredients: ["1/2 cup raw pumpkin seeds", "1 tsp olive oil", "1/2 tsp smoked paprika", "Pinch of salt"],
    instructions: ["Preheat oven to 350°F.", "Toss seeds with oil, paprika, salt.", "Spread on sheet pan.", "Roast 15 min stirring once."],
  },
  {
    id: "berrywalnuts",
    cat: "snacks",
    emoji: "🫐",
    title: "Berries with Walnuts",
    time: "1 min",
    calories: "180 cal",
    summary: "A bowl of fresh berries topped with chopped walnuts.",
    benefit: "Berries provide anthocyanins and walnuts bring omega-3s — a perfect heart snack.",
    ingredients: ["1 cup mixed berries", "2 tbsp chopped walnuts"],
    instructions: ["Combine in a bowl."],
  },
  {
    id: "crackerscheese",
    cat: "snacks",
    emoji: "🧀",
    title: "Whole Grain Crackers with Cheese",
    time: "2 min",
    calories: "200 cal",
    summary: "Fiber-rich whole grain crackers with a small portion of sharp cheddar.",
    benefit: "Whole grain crackers add fiber; a small amount of cheese satisfies with less saturated fat.",
    ingredients: ["6 whole grain crackers", "1 oz sharp cheddar", "Grapes on the side"],
    instructions: ["Arrange crackers and cheese on a plate.", "Add grapes for sweetness."],
  },
  {
    id: "darkchocalmonds",
    cat: "snacks",
    emoji: "🍫",
    title: "Dark Chocolate Covered Almonds",
    time: "10 min",
    calories: "190 cal",
    summary: "Homemade dark chocolate almonds — a healthier sweet treat.",
    benefit: "Dark chocolate (70%+ cacao) contains flavonoids that may support healthy blood flow.",
    ingredients: ["1/2 cup raw almonds", "2 oz dark chocolate (70%+)"],
    instructions: ["Melt chocolate in a double boiler.", "Stir in almonds to coat.", "Spread on parchment. Refrigerate 15 min."],
  },
  {
    id: "tunacucumber",
    cat: "snacks",
    emoji: "🥒",
    title: "Tuna Cucumber Boats",
    time: "5 min",
    calories: "180 cal",
    summary: "Hollowed cucumber halves filled with a light tuna salad.",
    benefit: "A low-carb protein boost that delivers omega-3s with every bite.",
    ingredients: ["1 cucumber, halved lengthwise and seeded", "1 can tuna in water", "1 tbsp Greek yogurt", "1 tsp Dijon", "1 tbsp chopped celery", "Dill"],
    instructions: ["Mix tuna, yogurt, Dijon, celery, dill.", "Spoon into cucumber halves."],
  },
  {
    id: "avoricecake",
    cat: "snacks",
    emoji: "🥑",
    title: "Smashed Avocado on Rice Cake",
    time: "3 min",
    calories: "150 cal",
    summary: "A crunchy rice cake topped with smashed avocado and sea salt.",
    benefit: "A light, low-calorie way to get avocado's healthy fats.",
    ingredients: ["2 brown rice cakes", "1/2 avocado, mashed", "Squeeze of lemon", "Sea salt", "Red pepper flakes"],
    instructions: ["Spread avocado on rice cakes.", "Top with lemon, salt, pepper flakes."],
  },
  {
    id: "tapenadecrackers",
    cat: "snacks",
    emoji: "🫒",
    title: "Olive Tapenade on Toast",
    time: "3 min",
    calories: "180 cal",
    summary: "Olive tapenade spread on whole-grain toast points.",
    benefit: "Olives are packed with monounsaturated fats and polyphenols — Mediterranean gold.",
    ingredients: ["1 slice whole-grain bread, toasted and cut into 4", "3 tbsp olive tapenade", "Fresh basil"],
    instructions: ["Spread tapenade on toast points.", "Garnish with basil."],
  },

  // ================================================
  // SMOOTHIES & DRINKS
  // ================================================
  {
    id: "smoothie",
    cat: "smoothies",
    emoji: "🫐",
    title: "Heart-Boost Berry Smoothie",
    time: "5 min",
    calories: "260 cal",
    summary: "A vibrant blend of berries, banana, and flaxseed for sustained energy.",
    benefit: "Berries are packed with anthocyanins that support arterial health. Flaxseed adds plant-based omega-3s.",
    ingredients: ["1 cup frozen mixed berries", "1/2 banana", "1 cup unsweetened almond milk", "1 tbsp ground flaxseed", "1 tbsp almond butter", "1/2 tsp vanilla extract"],
    instructions: ["Add everything to a blender.", "Blend until smooth.", "Pour and enjoy."],
  },
  {
    id: "greensmoothie",
    cat: "smoothies",
    emoji: "🥬",
    title: "Green Power Smoothie",
    time: "5 min",
    calories: "240 cal",
    summary: "A green smoothie you'll actually crave — banana and pineapple keep it sweet.",
    benefit: "Spinach brings folate and nitrates that support healthy blood pressure.",
    ingredients: ["2 cups spinach", "1/2 banana", "1/2 cup pineapple", "1 tbsp chia seeds", "1 cup coconut water", "1 tbsp almond butter"],
    instructions: ["Blend spinach and coconut water first.", "Add remaining ingredients and blend until smooth."],
  },
  {
    id: "beetberry",
    cat: "smoothies",
    emoji: "🫒",
    title: "Beet Berry Smoothie",
    time: "5 min",
    calories: "220 cal",
    summary: "An earthy-sweet blend of beet, berries, and ginger.",
    benefit: "Beets contain dietary nitrates that convert to nitric oxide — which helps blood vessels relax.",
    ingredients: ["1/2 small cooked beet", "1/2 cup frozen berries", "1/2 banana", "1 tsp grated ginger", "1 cup almond milk", "1 tbsp ground flax"],
    instructions: ["Blend all ingredients until smooth."],
  },
  {
    id: "turmeric",
    cat: "smoothies",
    emoji: "🥭",
    title: "Tropical Turmeric Smoothie",
    time: "5 min",
    calories: "250 cal",
    summary: "Mango, turmeric, and ginger in one golden smoothie.",
    benefit: "Turmeric contains curcumin, an anti-inflammatory compound studied for cardiovascular health.",
    ingredients: ["1 cup frozen mango", "1/2 banana", "1/2 tsp turmeric", "1/2 tsp ginger", "1 cup almond milk", "1 tbsp chia seeds", "Pinch of black pepper"],
    instructions: ["Blend all until smooth.", "The pepper helps your body absorb turmeric."],
  },
  {
    id: "cherryalmond",
    cat: "smoothies",
    emoji: "🍒",
    title: "Cherry Almond Smoothie",
    time: "5 min",
    calories: "270 cal",
    summary: "Tart cherries blended with almond butter and oats.",
    benefit: "Tart cherries contain anthocyanins and are studied for their heart and sleep-supporting benefits.",
    ingredients: ["1 cup frozen tart cherries", "1 tbsp almond butter", "2 tbsp rolled oats", "1 cup almond milk", "1 tsp honey"],
    instructions: ["Blend all until thick and smooth."],
  },
  {
    id: "cocoabanana",
    cat: "smoothies",
    emoji: "🍫",
    title: "Cocoa Banana Smoothie",
    time: "5 min",
    calories: "280 cal",
    summary: "Chocolate lover's smoothie, powered by unsweetened cocoa.",
    benefit: "Unsweetened cocoa is rich in flavanols shown to support healthy blood flow.",
    ingredients: ["1 frozen banana", "1 tbsp unsweetened cocoa", "1 tbsp almond butter", "1 cup almond milk", "1 tsp maple syrup", "1 tbsp ground flax"],
    instructions: ["Blend until smooth and creamy."],
  },
  {
    id: "avolime",
    cat: "smoothies",
    emoji: "🥑",
    title: "Avocado Lime Smoothie",
    time: "5 min",
    calories: "280 cal",
    summary: "A creamy, tangy smoothie with avocado and lime.",
    benefit: "Avocado makes smoothies silky while adding heart-supportive monounsaturated fats.",
    ingredients: ["1/2 avocado", "1/2 cup Greek yogurt", "1 cup spinach", "1 tbsp lime juice", "1 cup coconut water", "1 tsp honey"],
    instructions: ["Blend until completely smooth."],
  },
  {
    id: "pomberry",
    cat: "smoothies",
    emoji: "🍇",
    title: "Pomegranate Berry Blast",
    time: "5 min",
    calories: "240 cal",
    summary: "Pomegranate juice and berries make a powerful antioxidant drink.",
    benefit: "Pomegranate has been studied for its positive effects on heart health and blood pressure.",
    ingredients: ["1/2 cup pomegranate juice", "1/2 cup frozen mixed berries", "1/2 banana", "1/2 cup plain Greek yogurt", "1 tbsp chia seeds"],
    instructions: ["Blend all until smooth."],
  },
  {
    id: "mangospinach",
    cat: "smoothies",
    emoji: "🥭",
    title: "Mango Spinach Smoothie",
    time: "5 min",
    calories: "240 cal",
    summary: "A tropical green smoothie that tastes more like dessert.",
    benefit: "Spinach + mango delivers folate, vitamin C, and fiber in one glass.",
    ingredients: ["1 cup frozen mango", "1 cup spinach", "1/2 banana", "1 cup almond milk", "1 tbsp flaxseed"],
    instructions: ["Blend spinach and milk first.", "Add remaining ingredients; blend smooth."],
  },
  {
    id: "blueberryflax",
    cat: "smoothies",
    emoji: "🫐",
    title: "Blueberry Flax Smoothie",
    time: "5 min",
    calories: "260 cal",
    summary: "A simple blueberry smoothie supercharged with flax.",
    benefit: "Flaxseed adds soluble fiber and ALA omega-3s that support heart health.",
    ingredients: ["1 cup blueberries", "1/2 banana", "2 tbsp ground flaxseed", "1 cup almond milk", "1/2 cup plain yogurt"],
    instructions: ["Blend all until smooth."],
  },
  {
    id: "goldenmilk",
    cat: "smoothies",
    emoji: "🥛",
    title: "Golden Milk",
    time: "5 min",
    calories: "140 cal",
    summary: "A warm turmeric latte with coconut milk and spices.",
    benefit: "An anti-inflammatory drink built around turmeric and black pepper — perfect before bed.",
    ingredients: ["1 cup almond milk", "1 tsp turmeric", "1/2 tsp cinnamon", "1/4 tsp ginger", "Pinch of black pepper", "1 tsp honey"],
    instructions: ["Warm almond milk in a pot.", "Whisk in spices and honey.", "Simmer 2 min; pour into a mug."],
  },
  {
    id: "hibiscustea",
    cat: "smoothies",
    emoji: "🌺",
    title: "Hibiscus Iced Tea",
    time: "10 min",
    calories: "15 cal",
    summary: "A tart, ruby-red tea that's delicious iced or hot.",
    benefit: "Hibiscus tea has been studied for its support of healthy blood pressure.",
    ingredients: ["2 hibiscus tea bags", "4 cups water", "1 tsp honey (optional)", "Lemon wedge", "Ice"],
    instructions: ["Steep tea bags in hot water 10 min.", "Sweeten with honey if desired.", "Pour over ice with lemon."],
  },
  {
    id: "cucumbermint",
    cat: "smoothies",
    emoji: "🥒",
    title: "Cucumber Mint Water",
    time: "5 min prep",
    calories: "5 cal",
    summary: "A refreshing infused water for all-day hydration.",
    benefit: "Hydration is one of the simplest ways to support circulation and heart function.",
    ingredients: ["4 cups water", "1/2 cucumber, sliced", "10 mint leaves", "Ice"],
    instructions: ["Combine in a pitcher.", "Chill 30 min before drinking."],
  },
  {
    id: "greentea",
    cat: "smoothies",
    emoji: "🍵",
    title: "Green Tea Citrus Cooler",
    time: "10 min",
    calories: "20 cal",
    summary: "Iced green tea with fresh orange and lemon.",
    benefit: "Green tea catechins have been linked to healthy cholesterol levels.",
    ingredients: ["2 green tea bags", "3 cups water", "1 orange, sliced", "1 lemon, sliced", "Ice"],
    instructions: ["Steep tea 3 min; let cool.", "Add citrus slices.", "Chill and serve over ice."],
  },
  {
    id: "watermelon",
    cat: "smoothies",
    emoji: "🍉",
    title: "Watermelon Lime Refresher",
    time: "5 min",
    calories: "110 cal",
    summary: "A naturally sweet blend of watermelon and lime.",
    benefit: "Watermelon contains L-citrulline, an amino acid studied for its support of blood vessel health.",
    ingredients: ["3 cups cubed watermelon", "1 tbsp lime juice", "Fresh mint", "Ice"],
    instructions: ["Blend watermelon, lime, ice.", "Strain if desired. Garnish with mint."],
  },
  {
    id: "matcha",
    cat: "smoothies",
    emoji: "🍵",
    title: "Matcha Almond Latte",
    time: "5 min",
    calories: "90 cal",
    summary: "A creamy matcha latte made with unsweetened almond milk.",
    benefit: "Matcha delivers concentrated green tea catechins in every sip.",
    ingredients: ["1 tsp matcha powder", "1 cup almond milk, warmed", "1 tsp honey", "1/4 cup hot water"],
    instructions: ["Whisk matcha with hot water until frothy.", "Add warm almond milk and honey."],
  },

  // ================================================
  // SALADS
  // ================================================
  {
    id: "chickpeasalad",
    cat: "salads",
    emoji: "🥗",
    title: "Mediterranean Chickpea Salad",
    time: "10 min",
    calories: "340 cal",
    summary: "Chickpeas, cucumber, tomato, and feta in a lemon-olive dressing.",
    benefit: "Chickpeas + olive oil = classic Mediterranean fare linked to heart health.",
    ingredients: ["1 can chickpeas, drained", "1/2 cucumber, diced", "1 cup cherry tomatoes", "1/4 red onion, diced", "1/4 cup feta", "2 tbsp olive oil", "1 tbsp lemon juice", "Oregano"],
    instructions: ["Combine chickpeas, cucumber, tomato, onion, feta.", "Whisk oil, lemon, oregano.", "Toss to coat."],
  },
  {
    id: "kalecaesar",
    cat: "salads",
    emoji: "🥬",
    title: "Massaged Kale Caesar",
    time: "10 min",
    calories: "280 cal",
    summary: "Tender massaged kale with a lighter Caesar dressing.",
    benefit: "Kale is loaded with vitamin K and lutein — nutrients for vascular health.",
    ingredients: ["4 cups kale, stems removed", "2 tbsp olive oil", "1 tbsp lemon juice", "1 tbsp Greek yogurt", "1 clove garlic", "2 tbsp Parmesan", "1 tbsp pumpkin seeds"],
    instructions: ["Massage kale with 1 tbsp oil and salt 1 min.", "Whisk remaining oil, lemon, yogurt, garlic.", "Toss kale with dressing.", "Top with Parmesan and seeds."],
  },
  {
    id: "spinachstrawberry",
    cat: "salads",
    emoji: "🍓",
    title: "Spinach Strawberry Salad",
    time: "10 min",
    calories: "300 cal",
    summary: "Baby spinach with sliced strawberries, almonds, and goat cheese.",
    benefit: "Strawberries bring vitamin C and flavonoids; spinach adds folate.",
    ingredients: ["3 cups baby spinach", "1 cup sliced strawberries", "2 tbsp sliced almonds", "1 tbsp goat cheese", "2 tbsp olive oil", "1 tbsp balsamic vinegar", "1 tsp honey"],
    instructions: ["Whisk oil, vinegar, honey.", "Toss spinach with dressing.", "Top with strawberries, almonds, goat cheese."],
  },
  {
    id: "beetwalnut",
    cat: "salads",
    emoji: "🟣",
    title: "Beet & Walnut Salad",
    time: "10 min",
    calories: "320 cal",
    summary: "Roasted beets with walnuts and a balsamic vinaigrette.",
    benefit: "Beets deliver nitrates for circulation; walnuts add omega-3s.",
    ingredients: ["2 cups mixed greens", "1 cup roasted beets, cubed", "1/4 cup chopped walnuts", "2 tbsp goat cheese", "2 tbsp olive oil", "1 tbsp balsamic"],
    instructions: ["Arrange greens on plates.", "Top with beets, walnuts, goat cheese.", "Drizzle olive oil and balsamic."],
  },
  {
    id: "quinoablackbean",
    cat: "salads",
    emoji: "🌽",
    title: "Quinoa Black Bean Salad",
    time: "15 min",
    calories: "360 cal",
    summary: "A Tex-Mex inspired salad with quinoa, beans, corn, and lime.",
    benefit: "Quinoa and beans form a complete plant protein with tons of fiber.",
    ingredients: ["1 cup cooked quinoa", "1 cup black beans", "1/2 cup corn", "1/4 cup diced red pepper", "2 tbsp chopped cilantro", "2 tbsp olive oil", "2 tbsp lime juice", "1 tsp cumin"],
    instructions: ["Combine quinoa, beans, corn, pepper, cilantro.", "Whisk oil, lime, cumin.", "Toss and chill 10 min."],
  },
  {
    id: "cucumbertomato",
    cat: "salads",
    emoji: "🍅",
    title: "Cucumber Tomato Feta Salad",
    time: "8 min",
    calories: "220 cal",
    summary: "The ultimate simple Mediterranean salad.",
    benefit: "Fresh vegetables with olive oil is the essence of a heart-healthy diet.",
    ingredients: ["2 cucumbers, diced", "2 tomatoes, diced", "1/4 red onion, sliced", "1/4 cup feta", "2 tbsp olive oil", "1 tbsp red wine vinegar", "Oregano"],
    instructions: ["Combine all vegetables.", "Whisk oil, vinegar, oregano.", "Toss with feta."],
  },
  {
    id: "asiancabbage",
    cat: "salads",
    emoji: "🥢",
    title: "Asian Cabbage Salad",
    time: "10 min",
    calories: "260 cal",
    summary: "Crunchy napa cabbage with edamame, carrot, and sesame dressing.",
    benefit: "Cabbage is a cruciferous vegetable with glucosinolates studied for heart health benefits.",
    ingredients: ["3 cups shredded napa cabbage", "1/2 cup edamame", "1/2 cup shredded carrot", "2 tbsp sliced almonds", "2 tbsp low-sodium soy sauce", "1 tbsp sesame oil", "1 tbsp rice vinegar", "1 tsp honey"],
    instructions: ["Combine cabbage, edamame, carrot.", "Whisk dressing ingredients.", "Toss and top with almonds."],
  },
  {
    id: "beetgoat",
    cat: "salads",
    emoji: "🟣",
    title: "Roasted Beet Goat Cheese Salad",
    time: "45 min (with roasting)",
    calories: "330 cal",
    summary: "Sweet roasted beets with creamy goat cheese over arugula.",
    benefit: "Beets and arugula are both rich in nitrates, which help blood vessels relax.",
    ingredients: ["2 medium beets", "3 cups arugula", "2 tbsp goat cheese", "2 tbsp pistachios", "2 tbsp olive oil", "1 tbsp balsamic", "1 tsp honey"],
    instructions: ["Roast whole beets at 400°F 40 min; peel and slice.", "Toss arugula with oil, balsamic, honey.", "Top with beets, cheese, pistachios."],
  },
  {
    id: "whitebeansalad",
    cat: "salads",
    emoji: "🫛",
    title: "White Bean Tuna Salad",
    time: "10 min",
    calories: "370 cal",
    summary: "Italian-style bean and tuna salad with red onion and lemon.",
    benefit: "White beans are rich in potassium and magnesium, minerals crucial for blood pressure.",
    ingredients: ["1 can white beans, drained", "1 can tuna in water", "1/4 red onion, thinly sliced", "2 tbsp parsley", "2 tbsp olive oil", "1 tbsp lemon juice", "Salt and pepper"],
    instructions: ["Combine beans, tuna, onion, parsley.", "Dress with olive oil and lemon.", "Serve chilled or at room temperature."],
  },
  {
    id: "pomarugula",
    cat: "salads",
    emoji: "🍇",
    title: "Pomegranate Arugula Salad",
    time: "8 min",
    calories: "280 cal",
    summary: "Peppery arugula with pomegranate seeds and walnuts.",
    benefit: "Pomegranate seeds are antioxidant powerhouses linked to heart benefits.",
    ingredients: ["3 cups arugula", "1/3 cup pomegranate seeds", "2 tbsp chopped walnuts", "2 tbsp crumbled feta", "2 tbsp olive oil", "1 tbsp balsamic"],
    instructions: ["Toss arugula with oil and balsamic.", "Top with pomegranate, walnuts, feta."],
  },
  {
    id: "avograpefruit",
    cat: "salads",
    emoji: "🥑",
    title: "Avocado Grapefruit Salad",
    time: "10 min",
    calories: "300 cal",
    summary: "A bright, fresh salad with avocado, grapefruit, and mint.",
    benefit: "Grapefruit delivers vitamin C while avocado's fats help with nutrient absorption.",
    ingredients: ["2 cups mixed greens", "1 avocado, sliced", "1 grapefruit, segmented", "2 tbsp olive oil", "1 tbsp lime juice", "Fresh mint"],
    instructions: ["Arrange greens on a plate.", "Top with avocado, grapefruit segments.", "Drizzle olive oil and lime; garnish with mint."],
  },
  {
    id: "lentilwalnut",
    cat: "salads",
    emoji: "🫘",
    title: "French Lentil Walnut Salad",
    time: "15 min",
    calories: "350 cal",
    summary: "Earthy French lentils with walnuts and Dijon vinaigrette.",
    benefit: "Lentils and walnuts together give you fiber, plant protein, and omega-3s.",
    ingredients: ["1 cup cooked French lentils", "2 tbsp chopped walnuts", "2 tbsp chopped parsley", "1 tbsp Dijon", "2 tbsp olive oil", "1 tbsp red wine vinegar", "1 shallot, minced"],
    instructions: ["Whisk Dijon, oil, vinegar, shallot.", "Toss with lentils, walnuts, parsley.", "Let sit 5 min for flavors to meld."],
  },
  {
    id: "applewalnut",
    cat: "salads",
    emoji: "🍎",
    title: "Apple Walnut Spinach Salad",
    time: "8 min",
    calories: "320 cal",
    summary: "Baby spinach with crisp apple, walnuts, and blue cheese.",
    benefit: "Apples add soluble fiber; walnuts deliver heart-healthy omega-3s.",
    ingredients: ["3 cups baby spinach", "1 apple, sliced", "1/4 cup walnuts", "2 tbsp blue cheese", "2 tbsp olive oil", "1 tbsp apple cider vinegar", "1 tsp Dijon"],
    instructions: ["Whisk oil, vinegar, Dijon.", "Toss spinach with dressing.", "Top with apple, walnuts, blue cheese."],
  },
  {
    id: "threebean",
    cat: "salads",
    emoji: "🫘",
    title: "Three Bean Salad",
    time: "10 min",
    calories: "320 cal",
    summary: "A classic bean salad with a light vinaigrette.",
    benefit: "Triple the beans means triple the fiber and plant protein for cholesterol support.",
    ingredients: ["1 cup kidney beans", "1 cup garbanzo beans", "1 cup green beans, cooked", "1/4 red onion, diced", "2 tbsp olive oil", "2 tbsp red wine vinegar", "1 tsp Dijon", "Parsley"],
    instructions: ["Combine beans and onion.", "Whisk oil, vinegar, Dijon.", "Toss. Chill 15 min. Garnish with parsley."],
  },
  {
    id: "watermelonfeta",
    cat: "salads",
    emoji: "🍉",
    title: "Watermelon Feta Salad",
    time: "8 min",
    calories: "230 cal",
    summary: "Sweet watermelon with salty feta and fresh mint.",
    benefit: "Watermelon delivers hydration and citrulline, an amino acid that supports blood flow.",
    ingredients: ["3 cups cubed watermelon", "1/4 cup feta", "2 tbsp mint leaves", "1 tbsp olive oil", "1 tbsp lime juice"],
    instructions: ["Combine watermelon, feta, mint.", "Drizzle olive oil and lime.", "Serve chilled."],
  },
  {
    id: "citrusfennel",
    cat: "salads",
    emoji: "🍊",
    title: "Citrus Fennel Salad",
    time: "10 min",
    calories: "250 cal",
    summary: "Shaved fennel with orange segments and olives.",
    benefit: "Fennel is rich in fiber and potassium; citrus adds vitamin C and flavonoids.",
    ingredients: ["1 fennel bulb, thinly shaved", "2 oranges, segmented", "1/4 cup kalamata olives", "2 tbsp olive oil", "1 tbsp lemon juice", "Fresh parsley"],
    instructions: ["Arrange fennel, orange, olives on a plate.", "Drizzle with olive oil and lemon.", "Garnish with parsley."],
  },

  // ================================================
  // SOUPS & STEWS
  // ================================================
  {
    id: "lentil",
    cat: "soups",
    emoji: "🍲",
    title: "Cozy Lentil Stew",
    time: "35 min",
    calories: "350 cal",
    summary: "A warming, fiber-loaded stew that's gentle on the gut and heart.",
    benefit: "Lentils are rich in soluble fiber and plant protein — both linked to healthier cholesterol levels.",
    ingredients: ["1 cup green lentils", "1 onion, diced", "2 carrots, chopped", "2 celery stalks", "3 cloves garlic", "4 cups broth", "1 can diced tomatoes", "1 tsp cumin"],
    instructions: ["Sauté onion, carrot, celery in olive oil 5 min.", "Add garlic and cumin.", "Add lentils, broth, tomatoes.", "Simmer 25-30 min until tender."],
  },
  {
    id: "tomatobasil",
    cat: "soups",
    emoji: "🍅",
    title: "Tomato Basil Soup",
    time: "30 min",
    calories: "240 cal",
    summary: "A creamy tomato soup made without heavy cream.",
    benefit: "Cooked tomatoes release more lycopene — a powerful heart-healthy antioxidant.",
    ingredients: ["2 cans whole tomatoes", "1 onion, diced", "3 cloves garlic", "2 tbsp olive oil", "1/2 cup basil", "2 cups broth", "1/4 cup cashews (for creaminess)"],
    instructions: ["Sauté onion and garlic in oil 5 min.", "Add tomatoes and broth. Simmer 15 min.", "Soak cashews in hot water 10 min.", "Blend everything with basil until smooth."],
  },
  {
    id: "minestrone",
    cat: "soups",
    emoji: "🥣",
    title: "Vegetable Minestrone",
    time: "40 min",
    calories: "300 cal",
    summary: "A hearty Italian vegetable soup with beans and pasta.",
    benefit: "A soup that packs 6+ vegetables into one bowl plus fiber-rich beans.",
    ingredients: ["1 onion, diced", "2 carrots, chopped", "2 celery stalks", "1 zucchini, diced", "1 can diced tomatoes", "1 can white beans", "4 cups broth", "1/2 cup small pasta", "Basil"],
    instructions: ["Sauté onion, carrot, celery 5 min.", "Add zucchini, tomatoes, beans, broth.", "Simmer 20 min.", "Add pasta; cook 8 more min.", "Finish with basil."],
  },
  {
    id: "whitebeansoup",
    cat: "soups",
    emoji: "🫛",
    title: "Creamy White Bean Soup",
    time: "25 min",
    calories: "310 cal",
    summary: "A velvety white bean soup with rosemary and garlic.",
    benefit: "Pureed white beans give creaminess without any heavy cream — and lots of fiber.",
    ingredients: ["2 cans white beans", "1 onion, diced", "3 cloves garlic", "4 cups broth", "2 sprigs rosemary", "2 tbsp olive oil", "Salt and pepper"],
    instructions: ["Sauté onion and garlic in oil 5 min.", "Add beans, broth, rosemary.", "Simmer 15 min.", "Remove rosemary. Blend half the soup and return to pot."],
  },
  {
    id: "butternut",
    cat: "soups",
    emoji: "🎃",
    title: "Roasted Butternut Squash Soup",
    time: "50 min",
    calories: "260 cal",
    summary: "A creamy butternut soup with a hint of ginger.",
    benefit: "Butternut squash is rich in potassium and beta-carotene, both heart-supportive.",
    ingredients: ["1 butternut squash, cubed", "1 onion, diced", "2 cloves garlic", "1 tsp grated ginger", "4 cups broth", "2 tbsp olive oil", "1/4 cup coconut milk"],
    instructions: ["Roast squash at 400°F 30 min.", "Sauté onion, garlic, ginger in oil.", "Add squash and broth; simmer 10 min.", "Blend until smooth. Stir in coconut milk."],
  },
  {
    id: "mushroombarley",
    cat: "soups",
    emoji: "🍄",
    title: "Mushroom Barley Soup",
    time: "50 min",
    calories: "310 cal",
    summary: "A hearty, earthy soup with barley and a mix of mushrooms.",
    benefit: "Barley contains beta-glucans specifically linked to supporting healthy cholesterol.",
    ingredients: ["1 cup pearl barley", "2 cups mixed mushrooms, sliced", "1 onion, diced", "2 carrots, chopped", "3 cloves garlic", "6 cups broth", "2 tbsp olive oil", "Thyme"],
    instructions: ["Sauté onion, carrot, garlic 5 min.", "Add mushrooms; cook 5 more min.", "Add barley, broth, thyme.", "Simmer 40 min until barley is tender."],
  },
  {
    id: "blackbeansoup",
    cat: "soups",
    emoji: "🫘",
    title: "Smoky Black Bean Soup",
    time: "30 min",
    calories: "320 cal",
    summary: "A smoky, spiced black bean soup topped with avocado.",
    benefit: "Black beans are fiber champions, especially helpful for cholesterol management.",
    ingredients: ["2 cans black beans", "1 onion, diced", "3 cloves garlic", "1 tsp cumin", "1 tsp smoked paprika", "4 cups broth", "1 can diced tomatoes", "Avocado for topping"],
    instructions: ["Sauté onion, garlic, spices in oil 5 min.", "Add beans, tomatoes, broth.", "Simmer 20 min.", "Blend half for creaminess. Top with avocado."],
  },
  {
    id: "gazpacho",
    cat: "soups",
    emoji: "🍅",
    title: "Classic Gazpacho",
    time: "15 min prep",
    calories: "180 cal",
    summary: "A cold Spanish soup of raw tomatoes, cucumber, and pepper.",
    benefit: "Raw vegetables preserve all their vitamin C and antioxidants.",
    ingredients: ["4 large tomatoes", "1 cucumber", "1 bell pepper", "1 clove garlic", "2 tbsp olive oil", "1 tbsp red wine vinegar", "Salt", "Basil"],
    instructions: ["Blend all ingredients except basil until smooth.", "Chill at least 1 hour.", "Serve cold with torn basil."],
  },
  {
    id: "splitpea",
    cat: "soups",
    emoji: "🟢",
    title: "Classic Split Pea Soup",
    time: "1 hour",
    calories: "340 cal",
    summary: "A hearty split pea soup with carrots and celery.",
    benefit: "Split peas deliver 16g of fiber per cup and plenty of plant protein.",
    ingredients: ["1 1/2 cups dried split peas", "1 onion, diced", "2 carrots, chopped", "2 celery stalks", "6 cups broth", "2 cloves garlic", "1 bay leaf"],
    instructions: ["Sauté onion, carrot, celery, garlic in olive oil.", "Add peas, broth, bay leaf.", "Simmer 45 min until peas break down.", "Remove bay leaf. Season."],
  },
  {
    id: "turkeyveg",
    cat: "soups",
    emoji: "🦃",
    title: "Turkey Vegetable Soup",
    time: "40 min",
    calories: "290 cal",
    summary: "Lean ground turkey with a mix of vegetables and herbs.",
    benefit: "Lean turkey keeps saturated fat low while veggies pack in nutrients.",
    ingredients: ["1/2 lb lean ground turkey", "1 onion, diced", "2 carrots", "2 celery", "1 zucchini", "1 can diced tomatoes", "4 cups broth", "Italian seasoning"],
    instructions: ["Brown turkey in a pot; set aside.", "Sauté vegetables 5 min.", "Return turkey, add tomatoes and broth.", "Simmer 20 min."],
  },
  {
    id: "italianwedding",
    cat: "soups",
    emoji: "🥣",
    title: "Light Italian Wedding Soup",
    time: "40 min",
    calories: "320 cal",
    summary: "Mini turkey meatballs in a spinach and orzo broth.",
    benefit: "Small amounts of meatballs mean you get flavor without the saturated fat.",
    ingredients: ["1/2 lb lean ground turkey", "1 egg", "2 tbsp breadcrumbs", "6 cups broth", "1 cup spinach", "1/3 cup orzo", "1 carrot, diced"],
    instructions: ["Mix turkey, egg, breadcrumbs. Form tiny meatballs.", "Simmer carrot in broth 5 min.", "Add meatballs and orzo; simmer 10 min.", "Stir in spinach."],
  },
  {
    id: "chickpeastew",
    cat: "soups",
    emoji: "🧆",
    title: "Chickpea Vegetable Stew",
    time: "30 min",
    calories: "370 cal",
    summary: "A warming stew with chickpeas, kale, and tomatoes.",
    benefit: "Chickpeas and kale combine fiber, protein, and vitamin K — a heart health trifecta.",
    ingredients: ["2 cans chickpeas", "1 onion, diced", "3 cloves garlic", "2 cups kale, chopped", "1 can diced tomatoes", "3 cups broth", "1 tsp cumin", "1 tsp paprika"],
    instructions: ["Sauté onion, garlic, spices 3 min.", "Add tomatoes and broth. Simmer 10 min.", "Add chickpeas and kale. Simmer 10 more min."],
  },
  {
    id: "moroccan",
    cat: "soups",
    emoji: "🥘",
    title: "Moroccan Chickpea Soup",
    time: "35 min",
    calories: "360 cal",
    summary: "Fragrant and spiced with cumin, cinnamon, and ginger.",
    benefit: "Warming spices not only add flavor but contain compounds linked to heart health.",
    ingredients: ["2 cans chickpeas", "1 onion, diced", "1 carrot, chopped", "1 tsp cumin", "1 tsp cinnamon", "1/2 tsp ginger", "4 cups broth", "1 can diced tomatoes"],
    instructions: ["Sauté onion and carrot 5 min.", "Add spices; stir 30 sec.", "Add chickpeas, tomatoes, broth.", "Simmer 25 min."],
  },
  {
    id: "gingercarrot",
    cat: "soups",
    emoji: "🥕",
    title: "Ginger Carrot Soup",
    time: "35 min",
    calories: "220 cal",
    summary: "A silky soup of carrots, ginger, and a touch of coconut milk.",
    benefit: "Carrots deliver beta-carotene and fiber; ginger adds anti-inflammatory compounds.",
    ingredients: ["6 carrots, chopped", "1 onion, diced", "1 tbsp grated ginger", "4 cups broth", "1/4 cup coconut milk", "2 tbsp olive oil"],
    instructions: ["Sauté onion and ginger in oil 5 min.", "Add carrots and broth.", "Simmer 20 min until soft.", "Blend smooth. Stir in coconut milk."],
  },
  {
    id: "tuscanbean",
    cat: "soups",
    emoji: "🌿",
    title: "Tuscan White Bean Soup",
    time: "30 min",
    calories: "340 cal",
    summary: "Cannellini beans, kale, and tomato in an olive oil broth.",
    benefit: "A textbook Mediterranean soup — beans, greens, olive oil, all heart-friendly.",
    ingredients: ["2 cans cannellini beans", "2 cups kale", "1 can diced tomatoes", "3 cups broth", "3 cloves garlic", "3 tbsp olive oil", "Rosemary"],
    instructions: ["Sauté garlic and rosemary in oil 1 min.", "Add tomatoes and broth.", "Add beans; simmer 15 min.", "Stir in kale until wilted."],
  },
  {
    id: "cauliflowerleek",
    cat: "soups",
    emoji: "🌼",
    title: "Cauliflower Leek Soup",
    time: "35 min",
    calories: "230 cal",
    summary: "A creamy soup made entirely without cream.",
    benefit: "Cauliflower blends into a velvety texture while keeping calories and fat low.",
    ingredients: ["1 head cauliflower, chopped", "2 leeks, sliced", "3 cloves garlic", "4 cups broth", "2 tbsp olive oil", "Salt and pepper", "Chives"],
    instructions: ["Sauté leeks and garlic in oil 5 min.", "Add cauliflower and broth.", "Simmer 20 min until tender.", "Blend smooth. Garnish with chives."],
  },

  // ================================================
  // SIDES
  // ================================================
  {
    id: "roastedbrussels",
    cat: "sides",
    emoji: "🌱",
    title: "Roasted Brussels Sprouts",
    time: "25 min",
    calories: "140 cal",
    summary: "Crispy roasted brussels sprouts with balsamic glaze.",
    benefit: "Brussels sprouts are a cruciferous vegetable rich in fiber and sulforaphane.",
    ingredients: ["1 lb brussels sprouts, halved", "2 tbsp olive oil", "1 tbsp balsamic glaze", "Salt and pepper"],
    instructions: ["Preheat oven to 425°F.", "Toss sprouts with oil, salt, pepper.", "Roast 20 min cut-side down.", "Drizzle with balsamic glaze."],
  },
  {
    id: "garlicspinach",
    cat: "sides",
    emoji: "🥬",
    title: "Garlic Sautéed Spinach",
    time: "5 min",
    calories: "80 cal",
    summary: "Wilted fresh spinach with garlic and olive oil.",
    benefit: "A fast way to get a huge dose of folate, iron, and vitamin K.",
    ingredients: ["5 cups baby spinach", "2 cloves garlic, sliced", "2 tbsp olive oil", "Squeeze of lemon", "Salt"],
    instructions: ["Heat oil in a pan; sauté garlic 30 sec.", "Add spinach; toss until wilted, about 2 min.", "Finish with lemon and salt."],
  },
  {
    id: "steamedbroccoli",
    cat: "sides",
    emoji: "🥦",
    title: "Steamed Broccoli with Lemon",
    time: "8 min",
    calories: "90 cal",
    summary: "Simple steamed broccoli with a bright lemon finish.",
    benefit: "Broccoli is loaded with vitamin C, fiber, and sulforaphane.",
    ingredients: ["1 head broccoli, in florets", "1 tbsp olive oil", "1 tbsp lemon juice", "Lemon zest", "Salt"],
    instructions: ["Steam broccoli 5 min until bright green.", "Toss with oil, lemon juice, zest, salt."],
  },
  {
    id: "sweetpotatoes",
    cat: "sides",
    emoji: "🍠",
    title: "Roasted Sweet Potato Wedges",
    time: "35 min",
    calories: "210 cal",
    summary: "Crispy wedges with olive oil and smoked paprika.",
    benefit: "Sweet potatoes deliver potassium and beta-carotene; both support cardiovascular health.",
    ingredients: ["2 sweet potatoes, cut into wedges", "2 tbsp olive oil", "1 tsp smoked paprika", "1/2 tsp garlic powder", "Salt"],
    instructions: ["Preheat oven to 425°F.", "Toss wedges with oil and spices.", "Roast 25-30 min flipping once."],
  },
  {
    id: "caulirice",
    cat: "sides",
    emoji: "🌼",
    title: "Cauliflower Rice",
    time: "10 min",
    calories: "100 cal",
    summary: "A low-carb rice alternative sautéed with herbs.",
    benefit: "A great way to get more vegetables while cutting carbs when desired.",
    ingredients: ["1 head cauliflower, riced", "2 tbsp olive oil", "1 clove garlic", "Fresh parsley", "Salt"],
    instructions: ["Heat oil in a pan; add garlic.", "Add riced cauliflower; sauté 5 min.", "Finish with parsley and salt."],
  },
  {
    id: "quinoapilaf",
    cat: "sides",
    emoji: "🌾",
    title: "Lemon Herb Quinoa Pilaf",
    time: "20 min",
    calories: "220 cal",
    summary: "Fluffy quinoa with lemon zest and fresh herbs.",
    benefit: "Quinoa is a complete protein and a great base for heart-friendly meals.",
    ingredients: ["1 cup quinoa", "2 cups broth", "1 tbsp olive oil", "Zest of 1 lemon", "2 tbsp chopped parsley", "2 tbsp chopped mint"],
    instructions: ["Rinse quinoa. Simmer in broth 15 min.", "Fluff with a fork.", "Stir in olive oil, lemon zest, herbs."],
  },
  {
    id: "roastedasparagus",
    cat: "sides",
    emoji: "🥬",
    title: "Roasted Asparagus",
    time: "15 min",
    calories: "100 cal",
    summary: "Tender asparagus with Parmesan and lemon.",
    benefit: "Asparagus is rich in folate, a B-vitamin important for heart health.",
    ingredients: ["1 bunch asparagus, trimmed", "2 tbsp olive oil", "2 tbsp Parmesan", "1 tbsp lemon juice", "Salt"],
    instructions: ["Preheat oven to 425°F.", "Toss asparagus with oil and salt.", "Roast 10 min.", "Top with Parmesan and lemon."],
  },
  {
    id: "mashedcauli",
    cat: "sides",
    emoji: "🌼",
    title: "Mashed Cauliflower",
    time: "20 min",
    calories: "140 cal",
    summary: "A lighter alternative to mashed potatoes.",
    benefit: "All the comfort of mashed potatoes with fewer carbs and more vitamin C.",
    ingredients: ["1 head cauliflower, chopped", "2 tbsp olive oil", "2 cloves garlic", "2 tbsp Parmesan", "Chives"],
    instructions: ["Steam cauliflower 10 min until soft.", "Blend with olive oil, garlic, Parmesan.", "Top with chives."],
  },
  {
    id: "sauteedkale",
    cat: "sides",
    emoji: "🥬",
    title: "Sautéed Kale with Garlic",
    time: "10 min",
    calories: "120 cal",
    summary: "Tender kale with garlic and red pepper flakes.",
    benefit: "Kale is one of the most nutrient-dense greens on earth.",
    ingredients: ["1 bunch kale, chopped", "3 cloves garlic", "2 tbsp olive oil", "Red pepper flakes", "Lemon juice"],
    instructions: ["Heat oil; add garlic and pepper flakes.", "Add kale; toss 5 min until wilted.", "Finish with lemon."],
  },
  {
    id: "medveggies",
    cat: "sides",
    emoji: "🫑",
    title: "Mediterranean Roasted Veggies",
    time: "35 min",
    calories: "180 cal",
    summary: "A rainbow of roasted vegetables with olive oil and herbs.",
    benefit: "Roasted vegetables retain their fiber and deliver polyphenols from every color.",
    ingredients: ["1 zucchini, sliced", "1 bell pepper, chunks", "1 red onion, wedged", "1 cup cherry tomatoes", "3 tbsp olive oil", "1 tsp oregano", "Salt"],
    instructions: ["Preheat oven to 425°F.", "Toss vegetables with oil, oregano, salt.", "Roast 25 min stirring once."],
  },
  {
    id: "brownrice",
    cat: "sides",
    emoji: "🍚",
    title: "Herbed Brown Rice",
    time: "45 min",
    calories: "210 cal",
    summary: "Nutty brown rice tossed with fresh herbs and olive oil.",
    benefit: "Brown rice keeps the fiber-rich bran intact, slowing blood sugar response.",
    ingredients: ["1 cup brown rice", "2 cups broth", "1 tbsp olive oil", "2 tbsp parsley", "2 tbsp chives"],
    instructions: ["Simmer rice in broth 40 min.", "Fluff and stir in olive oil and herbs."],
  },
  {
    id: "grilledzucchini",
    cat: "sides",
    emoji: "🥒",
    title: "Grilled Zucchini Ribbons",
    time: "15 min",
    calories: "90 cal",
    summary: "Thin zucchini ribbons grilled with olive oil and herbs.",
    benefit: "Zucchini is low-calorie and high-water, perfect alongside any main.",
    ingredients: ["2 zucchini, sliced lengthwise", "2 tbsp olive oil", "1 tsp Italian seasoning", "Salt", "Lemon juice"],
    instructions: ["Brush zucchini with oil and seasoning.", "Grill 3 min per side.", "Finish with lemon and salt."],
  },
  {
    id: "carrotribbons",
    cat: "sides",
    emoji: "🥕",
    title: "Roasted Carrot Ribbons",
    time: "25 min",
    calories: "130 cal",
    summary: "Thinly sliced carrots roasted with olive oil and honey.",
    benefit: "Carrots offer beta-carotene and soluble fiber for a heart-friendly side.",
    ingredients: ["6 carrots, sliced into ribbons", "2 tbsp olive oil", "1 tsp honey", "1/2 tsp thyme", "Salt"],
    instructions: ["Preheat oven to 400°F.", "Toss carrots with oil, honey, thyme.", "Roast 20 min."],
  },
  {
    id: "wiltedgreens",
    cat: "sides",
    emoji: "🌿",
    title: "Wilted Mixed Greens",
    time: "8 min",
    calories: "110 cal",
    summary: "A mix of chard, kale, and spinach wilted with garlic.",
    benefit: "Combining leafy greens gives you a broader spectrum of vitamins and minerals.",
    ingredients: ["2 cups kale", "2 cups chard", "2 cups spinach", "3 cloves garlic", "2 tbsp olive oil", "Lemon"],
    instructions: ["Heat oil; sauté garlic 30 sec.", "Add greens in stages until wilted.", "Finish with lemon."],
  },
  {
    id: "acornsquash",
    cat: "sides",
    emoji: "🎃",
    title: "Baked Acorn Squash",
    time: "50 min",
    calories: "180 cal",
    summary: "Halved acorn squash baked with cinnamon and a touch of maple.",
    benefit: "Acorn squash is full of fiber, potassium, and beta-carotene.",
    ingredients: ["1 acorn squash, halved and seeded", "1 tbsp olive oil", "1 tsp cinnamon", "1 tbsp maple syrup", "Chopped pecans"],
    instructions: ["Preheat oven to 400°F.", "Brush cut sides with oil, cinnamon, syrup.", "Bake cut-side up 40 min.", "Top with pecans."],
  },
  {
    id: "succotash",
    cat: "sides",
    emoji: "🌽",
    title: "Edamame Corn Succotash",
    time: "15 min",
    calories: "180 cal",
    summary: "A modern twist on succotash with edamame instead of lima beans.",
    benefit: "Edamame brings complete plant protein; corn adds fiber and sweetness.",
    ingredients: ["1 cup edamame", "1 cup corn", "1/2 red pepper, diced", "1 tbsp olive oil", "1 tbsp lime juice", "Cilantro"],
    instructions: ["Sauté edamame, corn, pepper in oil 5 min.", "Finish with lime and cilantro."],
  },

];
